ON-3 [back] update necessity API
gongmyeong-study/orangenongjang pull request #39
Opened 2020-08-24 13:13 UTC by YeonghyeonKO

## Major Changes

**Backend**
- nongjang/necessity/models.py에서 **NecessityCounter table 삭제** (NecessityUser table의 count로 관리할 예정)

<br>

- **PUT** method (`/api/v1/necessity/{necessity_id}/`)를 통해 생필품을 수정하는 **update** 함수 생성
> Necessity table의 row는 삭제되지 않도록 하고, NecessityUser table의 기존 row는 삭제되면서 새롭게 추가되는 방식

<br>

### Minor Change
- NecessityUserLog table과 연동하여 activity_category=NecessityUserLog.UPDATE를 기록함.

![image](https://user-images.githubusercontent.com/46114393/91048569-d39bcb00-e656-11ea-8fdb-b5aaa8efcfa4.png)

2020-08-25 00:25 UTC, JSKeum commented on nongjang/necessity/views.py
> +            return Response(status=status.HTTP_409_CONFLICT)
`NecessityUserLog.objects.create` 에서도 IntegrityError가 발생하도록 한 건가요?? 그리고 혹시 `NecessityUserLog.objects.create`가 실행된 뒤 ` NecessityUser.objects.create`에서 except가 발생하면 로그는 생성된 다음에 IntegrityError가 발생하지 않나요?

2020-08-25 00:36 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +            return Response(status=status.HTTP_409_CONFLICT)
음 제가 일부러 아예 똑같은 생필품(안바꾸고 다시 저장)으로 수정도 가능하도록 해서(단, necessity table은 유지되고 necessityuser table의 id만 갱신) 순서는 상관없을거라고 보았는데 사실 그러면 except의 의미가 하나도 없긴 하네요

2020-08-25 00:38 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +            return Response(status=status.HTTP_409_CONFLICT)
아 원래 delete 및 create 함수 밑에 있었는데 새로운 생필품 name으로 업데이트하길래 위로 올린건데 차라리 기존 이름을 변수로 저장하고 나중에 호출하면 되겠네요

2020-08-25 02:46 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +            NecessityUserLog.objects.create(user=user, necessity=necessities_old, activity_category=NecessityUserLog.UPDATE)
IntegrityError가 발생했을 때 Log가 생성되지 않도록 **necessities_old**와 **necessities_new**를 구분하였습니다.

2020-08-26 12:21 UTC, davin111 requested changes
요거는 count API랑은 별개인 거죠? 그리고 PR 설명에, Jira 카드 url들도 달아주면 좋을 거 같아요! 전반적으로 불필요한 query가 넘 많이 날아가는 API인 거 같네용! 리뷰가 늦어서 죄송합니다!

2020-08-26 12:21 UTC, davin111 commented on nongjang/necessity/views.py
> +    # PUT /api/v1/necessity/{necessity_id}/
이거 기만적인 주석인 거 같아요, necessity_user_id 로 바꿔야할듯!

2020-08-26 12:21 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessities_old = Necessity.objects.get(pk=necessity_user.necessity.pk)
그냥 necesisty_user.necessity 로 접근하면 그 자체가 여기서 얻으려고 하는 것입니다. 이렇게 하면 불필요한 SELECT query가 하나 더 생깁니다.

2020-08-26 12:21 UTC, davin111 commented on nongjang/necessity/views.py
> +        if not name:
위에처럼 DB에 query하기 전에, 일단 front에서 오는 request가 정상적인지 체크하는 로직이 앞서는 것이 효율적일 것 같습니다.

2020-08-26 12:21 UTC, davin111 commented on nongjang/necessity/views.py
> +        except IntegrityError:
이거 너무 try-except가 광범위한데, 어디서 IntegrityError가 발생할 수 있다고 보는 건가요? NecessityUser? 필요한 부분만 묶는 게 좋을 것 같아요. 제 다른 부분의 리뷰들을 반영하면 결국 이 try-except 자체가 필요없어질 것 같긴 해서 이걸 적용하자는 건 아니지만, 진섭이가 https://github.com/gongmyeong-study/orangenongjang/pull/39#discussion_r475997364 여기서 짚어준 좋은 부분에 대한 고민은, transaction 이라는 것으로도 해결 가능하다는 점 말씀드릴게요.

2020-08-26 12:21 UTC, davin111 commented on nongjang/necessity/views.py
> +            NecessityUser.objects.create(user=user, necessity=necessities_new)
이거 굳이 delete 하고 create할 필요가 전혀 없을 거 같아요 ㅜㅜ 그냥 위에서 get한 NecessityUser의 column 값 수정해서 넣고 save() 하면 끝나는 거 같은데... Django 공식 문서 QuerySet 쪽의 save()나 update() 등 확인해보시면 좋을 듯합니다. 참고로 update()로 수정하면, 여러 row를 동시에 update할 수 있긴 한데, updated_at이 안바뀝니다.

2020-08-26 12:21 UTC, davin111 commented on nongjang/necessity/views.py
> +        return Response(self.get_serializer(necessity_user, many=True).data, status=status.HTTP_202_ACCEPTED)
202_ACCEPTED 보다는, 200_OK가 자연스러운 것 같습니다.

2020-08-26 12:34 UTC, davin111 commented
@YeonghyeonKO 근데 이 이슈 ON-3 가 아니라 https://orangenongjang.atlassian.net/browse/ON-4 이거에 해당하는 거 아닌가요? branch와 PR 내용이 근데 ON-3네요, 만약 잘못된 게 맞다면 이것 때매 PR 닫을 필요는 없고, 다음부터 참고하면 될 듯.

2020-08-26 13:28 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +    # PUT /api/v1/necessity/{necessity_id}/
수정했습니다.

2020-08-26 13:40 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessities_old = Necessity.objects.get(pk=necessity_user.necessity.pk)
necesisty_user.necessity로 접근하면 `TypeError: Field 'id' expected a number but got <Necessity: Necessity object (32)>.` 오류가 떠서 일부러 pk로 접근한건데 아예 이 자체가 필요없다는 말인가요?

2020-08-26 13:40 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        if not name:
수정하였습니다.

2020-08-26 14:06 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        except IntegrityError:
수정했습니다.

2020-08-26 14:06 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        return Response(self.get_serializer(necessity_user, many=True).data, status=status.HTTP_202_ACCEPTED)
수정했습니다

2020-08-26 14:07 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +    # PUT /api/v1/necessity/{necessity_id}/
수정했습니다.

2020-08-26 14:07 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        if not name:
수정했습니다.

2020-08-26 14:07 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        except IntegrityError:
수정했습니다.

2020-08-26 14:07 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        return Response(self.get_serializer(necessity_user, many=True).data, status=status.HTTP_202_ACCEPTED)
수정했습니다.

2020-08-26 14:20 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessities_old = Necessity.objects.get(pk=necessity_user.necessity.pk)
necessity_user.necessity 자체와 그 type을 print 찍어보시면 이해가 빨리 될 수 있습니다. 그냥 그 자체가 이미 여기서 얻으려고 하는 necessities_old에요. 글구 복수형이라서 혼란을 줄 수 있을 거 같아요.

2020-08-26 14:24 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessities_old = Necessity.objects.get(pk=necessity_user.necessity.pk)
근데 그러면 pk로 접근을 못하는건가요?

2020-08-26 14:28 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessities_old = Necessity.objects.get(pk=necessity_user.necessity.pk)
무슨 말인지 잘 모르겠군요 좀 더 풀어줄 수 있나요

2020-08-26 14:34 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessities_old = Necessity.objects.get(pk=necessity_user.necessity.pk)
아 아닙니다 이해했습니다.

2020-08-26 15:19 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +            NecessityUser.objects.create(user=user, necessity=necessities_new)
수정했습니다.

2020-08-27 02:59 UTC, davin111 requested changes

2020-08-27 02:59 UTC, davin111 commented on nongjang/necessity/views.py
> +        if not name:
이거 NecessityUser get 하기 전부터 진짜 맨 앞으로 땡기자는 거긴 했어요

2020-08-27 02:59 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
근데 이거 update 로직인데, necessity가 새로 생겨도 되는 건가요? 그리고 이런 경우라면 애초에 위에서 NecessityUser 존재 안 했을 거 같은데. 왜냐면 Necessity가 지워진 상황이라면 CASCADE니까 NecessityUser도 같이 지워졌을 거라.

2020-08-27 02:59 UTC, davin111 commented on nongjang/necessity/views.py
> +        NecessityUser.objects.filter(pk=pk).update(user=user, necessity=necessity_new)
update 쓸 수는 있는데, 앞선 이전 코멘트에서 언급했듯, 이렇게 하면 updated_at이 업데이트가 안 되는 문제가 있긴 해요. 현재로선 NecessityUser에 updated_at이 없으니 직접적인 문제는 없긴 한듯.

2020-08-27 02:59 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_user = NecessityUser.objects.get(pk=pk)
여기서 또 다시 get 할 필요가 없지 않나요. 혹시 저 위에서 `necessity_user`로 가져온 애가 update시킨 값이 안 바뀌어서 다시 가져오려는 건가요?(요건 답변 부탁) 만약 그렇다면, update를 쓰지 말고 그냥 attribute로 대입시켜서 save() 하면 한 번에 다 해결 가능할듯.

2020-08-27 02:59 UTC, davin111 commented on nongjang/necessity/views.py
> +        return Response(self.get_serializer(necessity_user.necessity, many=False).data)
many=False는 기본 값이라 명시 필요 없을 듯.

2020-08-27 03:24 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        if not name:
알겠습니다.

2020-08-27 03:24 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
수정하는 것 자체도 데이터라서 (가격 변동, 옵션 변경 등) 일부러 넣은건데 불필요한가요?

2020-08-27 03:24 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
necessity_user를 저장한 이유는 아래 log 만들 때 '기존 이름'을 업데이트하기 위함이었습니다.

2020-08-27 03:24 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
그리고 Necessity가 지워진 상황이라는건 무슨 상황인지요? NecessityUser는 지워지긴 합니다

2020-08-27 03:24 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        NecessityUser.objects.filter(pk=pk).update(user=user, necessity=necessity_new)
타임라인에서 업데이트 시간을 기록해서 따로 필요성을 느끼진 못했습니다. 필요하다면 아래 그림 참조해서 하겠습니다.
![image](https://user-images.githubusercontent.com/46114393/91380270-8fc7e200-e85f-11ea-9e37-ca220d6ce715.png)

2020-08-27 03:24 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessity_user = NecessityUser.objects.get(pk=pk)
4개 attribute 대입을 따로 해서 save하는게 빠른지 update 및 get을 하는게 빠른지 궁금합니다.

2020-08-27 03:24 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        return Response(self.get_serializer(necessity_user.necessity, many=False).data)
수정했습니다.

2020-08-27 13:02 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
Necessity를 get_or_create한다는 것은, create해야할 수도 있다는 상황임을 가정하는 건데요. 근데 애초에 create할 상황이면 로직이 여기까지 못 도달한다는 거예요. 왜냐면 위에 NecesistyUser를 get할 때 이미 not found로 빠졌을 거니까. Necessity가 삭제된 상황이면, [CASCADE](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.CASCADE)에 의해 NecessityUser도 삭제되었을 테니까요.

2020-08-27 13:03 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_user = NecessityUser.objects.get(pk=pk)
save하는 시점에 update query하나가 나가고, update하고 get하는 건 query 2개니까 당연히 전자입니다. Django에서 동작할 때 어떤 query 나가는지 console에 찍어볼 수도 있어요.

2020-08-27 13:10 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_user = NecessityUser.objects.get(pk=pk)
attribute 대입을 하는 코드에서는 query가 실행되지 않습니다. Django 전체적으로, 실제 query가 실행되는 타이밍이 언제인지를 얘기하는 https://docs.djangoproject.com/en/3.1/topics/db/queries/#querysets-are-lazy 가 되게 중요한 부분이에요. @YeonghyeonKO

2020-08-27 13:12 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_user = NecessityUser.objects.get(pk=pk)
글구 제가 맨 위에 (요건 답변 부탁)이라고 한 부분, 확인하고 답변 주시면 좋을 거 같아요. 애초에 왜 처음에 get을 여기서 해야겠다고 생각했는지가 궁금.

2020-08-27 13:14 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
아... 음... 이걸보다보니 좀 더 왜 create하려고 했는지는 제 나름대로 이해를 하긴 했는데요. 그런데 애초에 개인이 Necessity의 name, option, description, price를 막 수정해도 되나요?

2020-08-27 13:15 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
뭐 생성도 유저가 생성해달라는대로 생성해주니까, 그건 그렇다고 치고, 그러면 name, option 다 똑같은데 description에 띄어쓰기 같은 거만 달라도 다른 Necessity로 매번 취급한다는 건데, 이건 좀 문제 있지 않을까요.

2020-08-27 13:16 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
Necessity는 마치 가게의 재고 하나하나처럼, 운영 측에서 관리하는 걸로 정하고, 개인은 그걸 요청해서 추가는 할 수 있되, 바꾸지는 못한다가 맞을 거 같긴 해요. 애초에 이 API가 뭘 하고 싶어하는 건지에 대한 동의가 좀 필요하긴 한듯.

2020-08-27 13:18 UTC, davin111 commented on nongjang/necessity/views.py
> +        NecessityUserLog.objects.create(user=user, necessity=necessity_old, activity_category=NecessityUserLog.UPDATE)
그리고 Necessity 자체가 바뀌는 상황인데, 그러면 NecessityUserLog의 이 부분에 새로운 Necessity를 넣어야하는 것이 아닌가... 하는 생각도 드는데.

2020-08-27 13:19 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
만약에 그냥 개인이 맘대로 다 할 수 있는 걸로 하고 싶은 거라면, 걍 Necessity 개념 자체를 재정의하는 게 좋을 듯. 지금 어차피 개인이 맘대로 추가 다 할 수 있는데, Necessity와 NecessityUser 관계성이 좀 모호한 거 같기도 하고요.

2020-08-27 14:07 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        NecessityUserLog.objects.create(user=user, necessity=necessity_old, activity_category=NecessityUserLog.UPDATE)
근데 여기서 **<'yeonghyeon'님이 'banana'의 name, description을 수정했습니다.>** 도 생각해봤는데 지저분한 것 같아서 **< 'yeonghyeon'님이 'banana'를 수정했습니다. >** 이렇게 놔둔 상황입니다.

2020-08-27 14:07 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
근데 슬랙에서 말한 거 보니깐 실제 존재하는 물품에 대해서 띄어쓰기 하나만 달라져도 아예 다른 물품이 되어 난잡한 table이 된다는 것에는 공감합니다. 다만 description의 용도에 대해 생각해봤을 때, 저는 사람마다 다를 수 있다고 보아서 이 부분을 count처럼 빼면 훨씬 낫지 않을까 생각이 드네요.

2020-08-27 14:07 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
그리고 저는 유저가 오타냈을 때를 가정해봤는데, "커피"가 아니라 "귀끠"로 생필품을 생성했을 때는 이미 necessity table에 새로운 row가 생성된 상태라는 것에 주목했습니다. "귀끠"를 삭제버튼을 눌러 직접 지우고 "커피"를 추가 버튼을 눌러 생성하는 것보다는 수정해서 "커피"로 자동으로 update (기존에는 삭제 및 생성을 Django가 해주는 것이었지만 update에 눈을 뜸) 해주는 것이 이미 옵션이랑 가격, 설명까지 적은 유저 입장에서 번거로움을 덜어주는 일이라고 생각했습니다.

2020-08-27 16:16 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
네 일단 여러가지 생각이 들긴 하는데 일단 지금은 적당한 선에서 Django 코드만 좀 더 정리하고 일단 merge하고 보는 게 좋겠다 싶긴 해요.

2020-08-27 16:17 UTC, davin111 approved these changes

2020-08-28 00:38 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
음 그렇군요 그럼 일단 update 및 get 대신 attribute 대입 및 save로 수정해보겠습니다

2020-08-28 03:18 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessity_new, created = Necessity.objects.get_or_create(name=name, option=option,
여러가지 생각이 들지만... 일단은 merge하겠습니다.

2020-08-28 13:39 UTC, JSKeum approved these changes

2020-08-28 15:41 UTC, merged