ON-12 [back] Necessity Update API debugging
gongmyeong-study/orangenongjang pull request #44
Opened 2020-09-04 15:27 UTC by YeonghyeonKO

## Debugging History

참고 : [**Jira ON-12**](https://orangenongjang.atlassian.net/browse/ON-12)

**생필품 수정 기능**
- Necessity Update API([Jira ON-4](https://orangenongjang.atlassian.net/browse/ON-4))에 존재하던 오류 수정
> 기존에는 Necessity Table과 비교하여 중복된 생필품인지 아닌지를 체크했으나 이제는 NecessityUser table의 **necessity_id**와 새롭게 생성되거나 기존에 존재하여 호출된 necessity_new의 **id**를 비교하는 방식을 사용함.

2020-09-04 15:27 UTC, YeonghyeonKO commented
이렇게 디버깅하는 PR은 Label을 어떤 걸 달면 좋을까요? (bug는 맥락상 이상해서..)

2020-09-05 12:48 UTC, davin111 requested changes

2020-09-05 12:48 UTC, davin111 commented on nongjang/necessity/views.py
> +        if created or necessity_user.necessity_id != necessity_new.id:
근데 새로 생성이 된 necessity면, 당연히 기존에 이 id와 같은 게 있었을 수가 없지 않아? `if created` 만 있으면 되는 거 아니니

2020-09-05 12:50 UTC, davin111 commented
@YeonghyeonKO 근데 버그를 고치는 PR은 워낙 흔해서, 별다른 label을 달 필요가 없을듯? 글구 이럴 때 우리 https://gongmyeongstudy.slack.com/archives/C011CSJ7YBH/p1598170104002900 당시에 `fix/ON-12` 같은 식으로 하자고 했어! GitHub label도 만들고 싶다면 fix 정도 어떨까?

2020-09-05 13:21 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        if created or necessity_user.necessity_id != necessity_new.id:
necessity_new는 새로 생성되었을 수도, 기존의 것을 get한 걸 수도 있습니다. 따라서 created가 True이면 당연히 생성하고 그렇지 않더라도 기존의 것을 불러왔지만 수정한 내용과 다르면 로그를 생성하도록 바꿈

2020-09-05 13:23 UTC, YeonghyeonKO commented
@davin111 윽 fix였구나 분명히 feature랑 대비되는거 있었는데 못찾고 저걸로함 담부터 fix로 갑니다

2020-09-05 14:18 UTC, davin111 commented on nongjang/necessity/views.py
> +        if created or necessity_user.necessity_id != necessity_new.id:
아 처음에 `if created or necessity_user.necessity_id != necessity_new.id:`으로 봤다! 죄송합니다.

그런데 또 궁금한 게, 기존에 있던 걸 created 안 하고 get해왔어, 근데 그 말은 name, option, description, price 같은 사실상 그 Necessity의 모든 정보가 지금 요청 받아서 들어온 거랑 똑같다는 건데, 이 경우에 이건 수정이 아닌 거 아니야? 그냥 똑같은 변경을 한 번 더 요청한 거 아닌가. 그러니까 `necessity_user.necessity_id != necessity_new.id`의 상황이 존재할 수 없는 거 같은데, created가 False인 상황에선.

이거 직접 이런저런 케이스 테스트해봔? @YeonghyeonKO

2020-09-05 14:33 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        if created or necessity_user.necessity_id != necessity_new.id:
음 그니깐 created가 False임에도 불구하고 Necessity에서 꺼낸 necessity_new와 necessity_user의 necessity가 다른 경우가 존재하는데 그게 바로 다른 유저들은 등록했지만 해당 유저는 등록하지 않은 생필품이야 그래서 또 다시 생성하지 않고 (생성되지 않는다는 것이 맞지) 불러와서 해당 유저한테 있으면 else로 넘어가고 없으면 log를 생성한다는 뜻이야.
왜냐하면 다른 사람한테는 있지만 나한테는 없으면 생성되어야하고(엄밀히 말해서는 외래키로 호출하는거지만) 나한테 이미 있는거라면 update 동작 및 log 생성을 수행하면 안되니깐?

2020-09-06 05:45 UTC, davin111 approved these changes

2020-09-06 06:04 UTC, merged