ON-15 [front] HousePage & API request with house id
gongmyeong-study/orangenongjang pull request #45
Opened 2020-09-09 07:06 UTC by JSKeum

### 1. HousePage 추가
* 유저의 하우스 목록을 불러옵니다
* 버튼을 누르면 해당 하우스 id를 들고 main으로 이동합니다

### 2. Route 수정
*  '/' route를 MainPage에서 HousePage로 변경했습니다
* 메인 페이지는 '/main/:id' 로 url이 변경되었습니다

### 3. Necessity Create, Necessity Get, Necessity Log API request에 houseId param을 추가

### 수정 및 추가해야 할 것
* 유저의 house가 아닐 경우 /main 에서 다른 페이지(/house 같은)로 이동 시켜야 함
* 하우스 만들기 버튼을 넣어야 함 

현재 하우스 만드는 버튼이 없기 때문에 포스트맨으로 직접 House 만든 후 테스트 부탁드립니다

2020-09-09 07:51 UTC, YeonghyeonKO reviewed
혹시 House를 만드는 API 자체가 없는 것 같은데 만든 후 postman에서 테스트하라는 말인가요?

2020-09-09 07:51 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityItem/NecessityItem.tsx
> +  };
ReactElement는 더 최신 버젼에서 쓰이는 문법인가요?

2020-09-09 07:51 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityUpdateModal/NecessityUpdateModal.tsx
> +
NecessityUpdateModal 부분은 내 기존 branch에서 따온거지?? 이런 주석은 없애도 될 듯

2020-09-09 07:51 UTC, YeonghyeonKO commented on orange/src/store/actions/necessity/necessity.tsx
> +  name, option, description, price, houseId,
good

2020-09-09 15:52 UTC, YeonghyeonKO commented
엥 근데 conflicts 된거 있네요

2020-09-10 03:16 UTC, JSKeum commented
브랜치 ON-7 이랑 엮인 커밋 정리해서 다시 올렸습니다!

2020-09-10 19:36 UTC, davin111 approved these changes
houseId를 number로..!

2020-09-10 19:36 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +    houseId: string
근데 houseId 왜 number가 아닌 string으로 관리되는 거야? number가 맞을 거 같은데, 이거 서버 쪽에서 house 정보 그냥 받으면 string으로 와서 그렇게 했었니? number로 안 오나? 아무튼 string으로 오더라도 변환하는 게 좋을 거 같아 @JSKeum

2020-09-10 19:41 UTC, davin111 requested changes
이거 server랑 연동해서 동작시키는 것은 안 된 듯?? 그냥 연결 깨지는 거를 감안하는 건가? 궁금합니다. 그리고 설령 일시적으로 동작 안 되게 하는 거 그렇다하더라도, endpoint 지금 방식으로 바뀌는 건 안 맞는 거 같아요. 글구 House List를 server에서 받아오는 부분은 구현이 안 된 거 아니야?

2020-09-10 19:41 UTC, davin111 commented on orange/src/store/actions/necessity/necessity.tsx
> +) => (dispatch: Dispatch) => axios.post(`/api/v1/${houseId}/necessity/`, {
오잉 근데 이렇게 endpoint를 아예 바꾸는 이유 있어? `POST /api/v1/necessity/`는 유지하고 body만 추가로 보내면 될 거 같은데

2020-09-10 19:41 UTC, davin111 commented on orange/src/store/actions/necessity/necessity.tsx
> +export const getNecessity = (houseId: string) => (dispatch: Dispatch) => axios.get(`/api/v1/necessity/${houseId}/`)
여기도 왜 endpoint가 바뀌는지? 일단 이렇게 하면 현재로서 전혀 동작 못하지 않아? 서버에서 404 떠서. 그렇게 연결해서 test해본 것?

2020-09-10 19:41 UTC, davin111 commented on orange/src/containers/TimelinePage/TimelinePage.tsx
> +    axios.get(`/api/v1/necessity/${this.props.houseId}/log/`)
여기에도 house_id 들어가는 거 부자연스러운 거 같아요. param이나 body로 house_id를 넘겨야할듯. 설령 저기 id를 넣는다해도, 의미적으로 necessity_id가 들어가야할 거 같은 자리라서 이상한 듯 합니다.

2020-09-10 19:42 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +    houseId: string
서버 쪽에서 받는 부분 자체가 없는? 거 같군, 그냥 예상해서 짠 것인가 머지... 근데 서버에 이미 house 주는 API 너가 만들어놨자나?

2020-09-10 19:44 UTC, davin111 commented on orange/src/store/actions/necessity/necessity.tsx
> +export const getNecessity = (houseId: string) => (dispatch: Dispatch) => axios.get(`/api/v1/necessity/${houseId}/`)
마찬가지로 houseId는 param이나 body로 넘기는 게 좋을 듯합니다.

2020-09-11 02:22 UTC, JSKeum commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +    houseId: string
houseId number로 수정했습니다

2020-09-11 02:22 UTC, JSKeum commented on orange/src/store/actions/necessity/necessity.tsx
> +) => (dispatch: Dispatch) => axios.post(`/api/v1/${houseId}/necessity/`, {
body로 넣을게요

2020-09-11 02:23 UTC, JSKeum commented on orange/src/store/actions/necessity/necessity.tsx
> +export const getNecessity = (houseId: string) => (dispatch: Dispatch) => axios.get(`/api/v1/necessity/${houseId}/`)
param으로 넘길게요

2020-09-11 02:23 UTC, JSKeum commented on orange/src/containers/TimelinePage/TimelinePage.tsx
> +    axios.get(`/api/v1/necessity/${this.props.houseId}/log/`)
여기도 param으로 넘길게여

2020-09-11 02:26 UTC, JSKeum commented
House List를 server에서 받아오는 건 구현되어 있습니다!

2020-09-11 16:01 UTC, YeonghyeonKO approved these changes
작동시켜보았습니다. 메인 페이지를 누르면 House 선택 창으로 돌아가는 것도 좋네요.

2020-09-12 08:18 UTC, JSKeum commented on orange/src/components/HouseList/HouseList.tsx
> +  const returnUserHouses = houses?.map((house, index) => (
houses의 초기 state가 undefined인데 axios get은 비동기로 실행이 되어가지고 get이 완료되기 전에 `houses.map`에서 에러나지 않도록 optional chaining으로 썼어요
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

2020-09-18 16:07 UTC, davin111 approved these changes
리뷰가 넘 늦어 죄송합니다

2020-09-19 00:54 UTC, merged