ON-13 [back] user가 necessity 정보를 변경하는 것을 NecessityUser table만 update하는 구조로 바꾸기
gongmyeong-study/orangenongjang pull request #48
Opened 2020-10-11 12:45 UTC by davin111

# This PR is yet draft

2020-10-12 08:47 UTC, YeonghyeonKO requested changes
정말 고생하셨습니다! 저도 엄청나게 꼼꼼하게 리뷰하려고 노력했습니다. (이것저것 찾아보느라 2시간 걸린듯..)

2020-10-12 08:47 UTC, YeonghyeonKO commented on nongjang/necessity/models.py
> +        )
class Meta에서 unique_together 걸어줄 때는 tuple이 국룰인가 보군요.

2020-10-12 08:47 UTC, YeonghyeonKO commented on nongjang/necessity/models.py
> -    activity_category = models.CharField(max_length=50, choices=ACTIVITY_CATEGORY, default=CHANGE)
choices를 사용하는데 default가 있으니 이 경우에는 확실히 약간 어색하긴 하네요.

2020-10-12 08:47 UTC, YeonghyeonKO commented on nongjang/necessity/models.py
> +        )
어 근데 공식문서 보니깐 여긴 list군요. 또한 unique_together 대신 UniqueConstraint를 권장하고 있습니다. (deprecated 될 수도 있다고 협박하는 [Django](https://docs.djangoproject.com/en/3.1/ref/models/options/#unique-together))

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/46114393/95721720-f4bf8600-0cad-11eb-8d4a-b3b8a9d717de.png">

2020-10-12 08:47 UTC, YeonghyeonKO commented on nongjang/necessity/models.py
> +    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
위의 db_index 질문과 비슷한 맥락인데, 하필 created_at field에 index를 넣은 이유가 궁금합니다.

2020-10-12 08:47 UTC, YeonghyeonKO commented on nongjang/necessity/serializers.py
> +        return necessity_house.price if necessity_house.price else necessity_house.necessity.price
necessity_house.description은 house에 대한 설명이고, necessity_house.necessity.description은 house에서 관리하고 있는 necessity에 대한 설명은 아닌 것 같은데, 후자는 직관적으로 이해가 가는데 전자가 잘 이해가 안되어 어디서 받아오는 객체인지 질문드립니다.

2020-10-12 08:47 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        return super(NecessityViewSet, self).get_permissions()
is_staff가 괜히 있는 field가 아니었군요...
<img width="844" alt="image" src="https://user-images.githubusercontent.com/46114393/95724850-da87a700-0cb1-11eb-919e-73a8a59ef79f.png">

출처 : https://www.django-rest-framework.org/api-guide/permissions/

2020-10-12 08:47 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        if name is not None or description is not None or price is not None:
description은 항상 request에서 받은 Char 또는 blank가 되는게 아닌가요? None인 경우가 의아합니다.

2020-10-12 08:47 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessity_house.count = 0
사용자가 House의 necessity를 삭제한다고 해도 실제로 삭제되지는 않고 count가 0으로 바뀌는 로직은 이해가 가는데, 이 상황이면 수량이 0인 상태로 front에서 보이는 상태 아닌가요?

2020-10-12 11:07 UTC, davin111 commented on nongjang/house/serializers.py
> +        )
@YeonghyeonKO 아 이런 정보 있으면 활용할만 하겠네요. 반영할게.

2020-10-12 11:13 UTC, davin111 commented on nongjang/house/views.py
> +        necessity_id = data.get('necessity_id')
@YeonghyeonKO  응, 많은 웹이나 앱이 그렇듯 frontend에서 유저가 타이핑할 때 자동완성 되듯 이미 DB에 있는 Necessity들 중 string matching되는 걸 보여주고 User가 그 중에 택하면 그 necessity_id를 frontend에서 쏴주고, 직접 그냥 입력하면 name을 주는 것 정도로 구현할 수 있겠지.

2020-10-12 11:14 UTC, davin111 commented on nongjang/house/views.py
> +        name = data.get('name')
그런 걸 체크하는 것보다는 그냥 길이가 지나치게 긴 경우 등 정도만 간단히 생각하긴 했습니다.

2020-10-12 11:15 UTC, davin111 commented on nongjang/house/views.py
> +        count = data.get('count')
@YeonghyeonKO 네 물론 frontend에서 그걸 입력하라고 하고 받아서 쏴줘야겠지요. 그리고 코드 보면 알 수 있듯, 기존에 존재하는 Necessity의 경우에도 이 입력을 모두 받습니다. 특히 count는 어떤 경우든 필수입니다.

2020-10-12 11:16 UTC, davin111 commented on nongjang/house/views.py
> +            return Response({'error': "necessity_id 또는 name이 요청에 포함되어야 합니다."}, status=status.HTTP_400_BAD_REQUEST)
아마 그 예시 중 하나가 https://github.com/gongmyeong-study/orangenongjang/pull/48#discussion_r503222354 이런 구현이겠지.

2020-10-12 11:19 UTC, davin111 commented on nongjang/necessity/models.py
> +    updated_at = models.DateTimeField(auto_now=True, db_index=True)
User가 NecessityHouse를 '삭제'한다고 해도, 실제로 그 count를 0으로 설정하는 것입니다. 그리고 House에 속한 Necessity를 보려는 `GET /api/v1/house/{house_id}/necessity/`는 https://github.com/gongmyeong-study/orangenongjang/pull/48/files#diff-432f678ba369c6355ef35063512802b4R44 를 보면 알 수 있듯, 내부적으로 `count__gt=0` 같은 query를 사용합니다. frontend에서 자주 call할 API이며, NecessityHouse의 row는 꽤 많아질 수 있다고 판단해 넣었습니다.

updated_at도 같은 line에서 수정한 최신순으로 정렬해서 줄 때 사용하기에 추가했습니다.

2020-10-12 11:20 UTC, davin111 commented on nongjang/necessity/models.py
> +        )
ㅋㅋㅋ 어쨌든 우리가 쓰는 Django 버전에서 사라지는 일은 없을테니 괜찮을 거 같구요, Python에서 [] 는 가변적인데 tuple은 불변이라(예를 들어 list는 append 등으로 원소의 개수 등이 바뀔 수 있음) 사실 성능상 미묘한 차이가 있습니다. 이렇게 안 바뀔 iterable은 tuple을 쓰는 것이 좋습니다.

2020-10-12 11:21 UTC, davin111 commented on nongjang/necessity/models.py
> -    activity_category = models.CharField(max_length=50, choices=ACTIVITY_CATEGORY, default=CHANGE)
아 choices와 default의 궁합은 나쁘지 않은 것 같은데, 그냥 굳이 필요가 없는 것 같아 뺐습니다. 뭔가 기본으로 삼기에 다 애매한 상태들이라서요.

2020-10-12 11:22 UTC, davin111 commented on nongjang/house/views.py
> +        logs = NecessityLog.objects.filter(necessity_house__house=house).select_related('necessity_house')
여기에 생성한 최신이 위에 오도록 order_by가 들어가게 수정할 예정.

2020-10-12 11:23 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +        name = data.get('name')
아하 알겠습니다.

2020-10-12 11:23 UTC, davin111 commented on nongjang/necessity/views.py
> +        if name is not None or description is not None or price is not None:
request body에 해당 key 자체가 없으면 None입니다.
description key가 있는데 value가 없으면 blank('')입니다.

2020-10-12 11:24 UTC, davin111 commented on nongjang/necessity/views.py
> +        return super(NecessityViewSet, self).get_permissions()
Django admin이라는 매우 강력한 툴을 개발해두면 이를 사용하는 운영진? 들이 보통 is_staff=True 이기도 합니다.

2020-10-12 11:25 UTC, davin111 commented on nongjang/necessity/models.py
> +    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
https://github.com/gongmyeong-study/orangenongjang/pull/48/files#diff-c0b28dfba7356bf14c8adc53994a0831R174 아 ㅋㅋㅋ 원래 이 line에 order_by('-created_at') 으로, 생성된 최신 log부터 보이게 하려고 했는데 빠뜨렸네요. 암튼 그래서 넣었습니다. order_by 자주 걸 field에는 넣는 게 좋습니다.

2020-10-12 11:25 UTC, YeonghyeonKO commented on nongjang/necessity/models.py
> +    updated_at = models.DateTimeField(auto_now=True, db_index=True)
아 그렇군요... count__gt=0 이건 정말 생각도 못해봤네요. 부하라고 하면 항상 front에서 일어날법한 개념으로 생각했었는데 그 내부 동작에 있어서 count를 index 처리하면 빨라지는지 처음 알았습니다.

2020-10-12 11:26 UTC, YeonghyeonKO commented on nongjang/necessity/models.py
> +        )
아하 pythonic한 조언 감사합니다

2020-10-12 11:27 UTC, YeonghyeonKO commented on nongjang/house/serializers.py
> +        )
넵 실제로 이삿날에 잠깐 얘기했던 것 같습니다

2020-10-12 11:28 UTC, davin111 commented on nongjang/necessity/serializers.py
> +        return necessity_house.price if necessity_house.price else necessity_house.necessity.price
후자와 전자가 뭐가 뭔지 좀 헷갈리는데 그냥 설명하자면,

description과 price는 https://github.com/gongmyeong-study/orangenongjang/pull/48/files#r503223382 여기에서 언급했듯, House에 Necessity를 새로 생성해서 NecessityHouse를 생성하든, 기존에 있던 Necessity로 NecessityHouse를 생성하든 입력할 수 있습니다.

유저가 직접 기재한 NecessityHouse의 description, price 정보가 없으면 그냥 비우지 말고 해당 Necessity 자체의 그 값들 각각을 보여주자는 것입니다. default 값을 주려는 의도.

2020-10-12 11:29 UTC, davin111 commented on nongjang/necessity/views.py
> +        necessity_house.count = 0
https://github.com/gongmyeong-study/orangenongjang/pull/48/files#diff-432f678ba369c6355ef35063512802b4R44

2020-10-12 11:30 UTC, davin111 commented on nongjang/house/views.py
> +            return Response({'error': "집에 이미 존재하는 Necessity 정보입니다."}, status=status.HTTP_409_CONFLICT)
NecessityHouse 말인가요? https://github.com/gongmyeong-study/orangenongjang/pull/48/files#diff-fed7a0ce135e0402ae83d3b1c3207d6fR30 에서 볼 수 있듯, 그리고 error 메시지가 말하듯 house, necessity가 함께 unique 입니다.

2020-10-12 11:32 UTC, davin111 commented
@YeonghyeonKO 꼼꼼한 리뷰 매우 감사합니다. 개발할 맛이 나는군 ㅎㅎ

2020-10-12 14:43 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +            return Response({'error': "집에 이미 존재하는 Necessity 정보입니다."}, status=status.HTTP_409_CONFLICT)
오 그렇군요... unique_together가 비록 index를 생성하진 않더라도 IntegrityError 기능은 가지고 있군요

2020-10-12 14:49 UTC, YeonghyeonKO commented on nongjang/necessity/serializers.py
> +        return necessity_house.price if necessity_house.price else necessity_house.necessity.price
아 이해했습니다. Necessity를 admin이 생성할 때 넣어준 값을 default로 쓰자는 얘기군요. 그러면 현재 제가 NecessityCreateModal 만든 것에서 회색으로 default 보이는거랑 비슷한 방식이네요. 물론 아예 necessity 생성 방식이 달라질 수도 있지만

2020-10-12 14:49 UTC, YeonghyeonKO commented on nongjang/necessity/serializers.py
> +        return necessity_house.price if necessity_house.price else necessity_house.necessity.price
와 이런 논리들 다 어케 생각한거 ㅋㅋㅋㅋ 물론 생각할 수 있는데 시간이 ㄷㄷ

2020-10-12 14:51 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        if name is not None or description is not None or price is not None:
음 그런가요 저는 python get함수가 data라는 dictionary에서 'description'이라는 key가 없으면 None을 반환하는데, 그 경우에 두 번째 인자를 지정해주면 None 대신 두 번째 인자를 반환하는 것으로 생각했습니다.

2020-10-13 03:40 UTC, YeonghyeonKO approved these changes
LGTM

2020-10-13 03:40 UTC, YeonghyeonKO commented on nongjang/house/serializers.py
> +        )
Good. postman으로도 확인했습니다!
<img width="508" alt="image" src="https://user-images.githubusercontent.com/46114393/95812776-145bba80-0d51-11eb-9f0d-f351ccbb8759.png">

2020-10-13 04:24 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +            return Response({'error': "집에 이미 존재하는 Necessity 정보입니다."}, status=status.HTTP_409_CONFLICT)
다음은 (1) name="생수", description="삼다수", option="2L", price=700를 admin에 의해 생성한 다음, 
(2) user가 house necessity로 admin이 생성한 "생수"의 necessity_id 값을 받아 description, count를 변경하여 "생수"를 넣은 후
(3) 다른 회사("쿠팡 탐사수")의 생수를 house necessity로 입력하려는 상황입니다.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/46114393/95814048-62be8880-0d54-11eb-93d5-b5b2e9004979.png">

<img width="871" alt="image" src="https://user-images.githubusercontent.com/46114393/95814204-c8ab1000-0d54-11eb-9917-878b4c326151.png">


<img width="1009" alt="image" src="https://user-images.githubusercontent.com/46114393/95814033-59352080-0d54-11eb-850a-26c7df7d444f.png">

현재 로직대로라면 당연히 IntegrityError 때문에 다음과 같은 409 Conflict가 반환되는게 맞습니다.

이런 상황에서 다른 브랜드의 생수를 추가하는 방법은 다음과 같이 necessity_id를 받지 않고 직접 Necessity table에 생성하는 방식입니다. 
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/46114393/95814455-6bfc2500-0d55-11eb-87c7-530ba8a608ec.png">


추후에 로직을 수정하는 것이 좋을지 아니면 지금 로직대로 가고 사용자들에게 "{username}님의 {house_name}에는 이미 같은 생필품이 존재합니다. 같은 이름의 다른 브랜드나 옵션, 가격의 생필품을 입력하고 싶으시면 직접 생성하세요!" 를 띄워주는 방식이 좋을까요? 후자는 너무 번거로울 것 같다는 생각이 듭니다.

2020-10-13 04:24 UTC, YeonghyeonKO commented on nongjang/necessity/views.py
> +        necessity_house.count = 0
음 사실상 count가 0이면 의미가 형태는 없는 상황이니 없앤거나 마찬가지라고 보겠다는 거군요

2020-10-13 11:22 UTC, davin111 commented on nongjang/necessity/serializers.py
> +        return necessity_house.price if necessity_house.price else necessity_house.necessity.price
@YeonghyeonKO 하다보면 거의 필연적으로 짜게 되고, 애매하게 해서 이상하게 구현되는 것보다 이게 훨씬 효율적!

2020-10-13 11:22 UTC, davin111 commented on nongjang/house/views.py
> +            return Response({'error': "집에 이미 존재하는 Necessity 정보입니다."}, status=status.HTTP_409_CONFLICT)
@YeonghyeonKO unique 걸면 index가 내재적으로 생성된다고 알고 있음

2020-10-13 11:23 UTC, davin111 commented on nongjang/necessity/views.py
> +        if name is not None or description is not None or price is not None:
@YeonghyeonKO 아아 그 말이군 그게 맞긴 함, 여기서 none 될 일은 없긴 하겠네. 나중에 수정할게.

2020-10-13 11:24 UTC, davin111 commented on nongjang/house/views.py
> +            return Response({'error': "집에 이미 존재하는 Necessity 정보입니다."}, status=status.HTTP_409_CONFLICT)
@YeonghyeonKO 이건 사실 '브랜드'를 저장할 것인지, 저장하면 어디 저장할 것인지부터 정의해야 문제인지 아닌지를 판단할 수 있다고 생각하는데, 아직 이에 대한 합의가 이뤄진 적이 없음. 지금의 질문은 그냥 brand를 description에 저장한다고 스스로 생각한 거 같은데, 난 여기에 동의하지 않음. brand를 저장할 거면 해당 column 을 따로 파는 게 더 좋다고 생각하고, brand는 아예 새로운 model로 만들 수도 있다고 생각함. 어쨌든 나중에 고려하는 게 적절하다고 생각.

2020-10-13 11:44 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +            return Response({'error': "집에 이미 존재하는 Necessity 정보입니다."}, status=status.HTTP_409_CONFLICT)
좋아요

2020-10-13 22:49 UTC, davin111 commented on nongjang/necessity/views.py
> +        if name is not None or description is not None or price is not None:
@YeonghyeonKO 그 외에도 부실한 부분 있어서 수정함. 이런 부분은 나중에 serializer로 write하는 게 나을 듯.

2020-10-13 22:50 UTC, merged