ON-19 [front] Changing frontend codes according to updated backend API
gongmyeong-study/orangenongjang pull request #54
Opened 2020-10-18 17:23 UTC by YeonghyeonKO

## Major Changes
### 0. 개요
- [ON-13](#48 )에서 생필품 생성 시 NecessityUser table로 관리하던 기존의 방식에서 NecessityHouse table에 저장하는 것으로 바꾸었습니다. 회원가입 및 로그인까지 작동되는 상태에서 더 나아가 클라이언트에서의 생필품 생성 및 수정, 수량 증감 기능을 backend와 연결할 필요가 있었습니다.

### 1. 생필품 생성 및 수정 프론트엔드 작업
- 대규모 리팩토링 작업이었던 [ON-20](#48)에 맞추어 Frontend 코드를 수정하였습니다. (ON-20 진행 이전 모습대로 복구하였습니다.)
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/46114393/96374945-d7f4e800-11b0-11eb-8b22-3736cd16e8bb.png">

<br>

## Minor Changes
- createNecessity, removeNecessity, countNecessity 함수의 이름을 각각 createHouseNecessity, removeHouseNecessity, countHouseNecessity로 수정하였습니다.
- Props에서 타입을 지정해주는 함수의 경우 "on"을 함수명 앞에 붙였습니다. (count 관련 함수는 [ON-11](#47)에서 한꺼번에 처리할 예정입니다.)

<br>

## What to do Next
- [ON-11](#47)과 더불어 Necessity 삭제 및 수량 증감 시 map으로 necessities array가 들어오지 않고 단일 necessity만 들어와 렌더링되지 않는 현상을 해결할 예정입니다.

<br>

## Discussions
- 생필품 생성 시(Necessity table에 없는 경우) count가 0인 경우 Necessity, NecessityHouse, NecessityLog table에 모두 object가 생성되는 것을 확인했습니다. 다만 화면에는 보이지 않는 현상이 발생하는데, 원인을 모르겠습니다. 
- 현재 생필품 수량이 0인 생필품을 생성한 후 (또는 생필품 삭제 API를 통해 수량을 0으로 만든 후) 다시 생필품을 만들려고 하면 "이미 존재하는 생필품입니다."라는 문구가 뜨게 됩니다. 이에 대한 논의 및 해결도 필요할 것 같습니다.

2020-10-18 17:38 UTC, davin111 requested changes

2020-10-18 17:38 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
요 부분 parseFloat() 쓰는 이유가 무엇인가요? 어차피 사실 int만 넘겨야 맞는 값인데

2020-10-18 17:38 UTC, davin111 commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
> +  counter: (houseId: number, necessityId: number, count: number): void => dispatch(
onCountHouseNecessity 같은 식의 이름으로 통일합시다.

2020-10-18 17:38 UTC, davin111 commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
> +  increase: (houseId: number, necessityId: number, count: number): void => dispatch(
이거 세 개가 동일한데, onCountHouseNecessity 로 하나만 정의하면 될 거 같네요. increase, decrease 등의 동작은 위에서 + 1, - 1 한 걸로 이미 구분이 된 것 같고.

2020-10-18 17:38 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
그냥 input 자체가 양의 정수만 들어오게, https://stackoverflow.com/questions/8808590/html5-number-input-type-that-takes-only-integers 등을 참고하고 min도 0으로 설정하면 좋을듯.

2020-10-18 17:38 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
>    create: (
onCreateHouseNecessity. 근데 NecessityHouse, HouseNecessity 순서가 혼용되지 않는지 체크해봐야할듯.

2020-10-18 17:38 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> -        console.log(this.props.createStatus);
good

2020-10-18 17:38 UTC, davin111 commented on orange/src/components/Necessity/NecessityList/NecessityList.tsx
> +          <div className="necessity-item-block">
요거 td가 div로 바뀐 이유는 무엇인가요?

2020-10-18 17:38 UTC, davin111 commented on orange/src/containers/NecessityPage/NecessityPage.tsx
> +  onGetNecessity: (houseId: number): void => dispatch(
임의로 바꾸기보다 action 이름을 그대로 살리는 게 혼동이 없을 듯. onGetHouseNecessity

2020-10-18 17:38 UTC, davin111 commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
> +  increase: (houseId: number, necessityId: number, count: number): void => dispatch(
아 ON-11 에서 처리한다고 하시긴 했네요, 그럼 그 때 참고하셔도 좋구요.

2020-10-18 17:40 UTC, davin111 commented
@YeonghyeonKO Discussions에 있는, `생필품 생성 시(Necessity table에 없는 경우) count가 0인 경우 Necessity, NecessityHouse, NecessityLog table에 모두 object가 생성되는 것을 확인했습니다. 다만 화면에는 보이지 않는 현상이 발생하는데, 원인을 모르겠습니다.` 내용은 backend에서 count 0이면 없는 걸로 치고 frontend에 response로 안 주게 로직이 되어있으니 정상적인 현상 아니에요? 처음에 count 0으로 받아서 생성하면 현재 서버 로직으로는 그래서 이상하긴 한듯?

2020-10-18 17:43 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
> +  counter: (houseId: number, necessityId: number, count: number): void => dispatch(
"count 관련 함수는 [ON-11](#47)에서 한꺼번에 처리할 예정입니다" 적어두긴 했는데 지금 바꾸는게 낫나요

2020-10-18 17:43 UTC, davin111 commented
`현재 생필품 수량이 0인 생필품을 생성한 후 (또는 생필품 삭제 API를 통해 수량을 0으로 만든 후) 다시 생필품을 만들려고 하면 "이미 존재하는 생필품입니다."라는 문구가 뜨게 됩니다. 이에 대한 논의 및 해결도 필요할 것 같습니다.` ㅇㅎ 이 부분은 정말로 고려가 필요하겠네요. 이거는 서버쪽 로직을 바꿔주면 좋을 듯. 이미 해당 생필품이 그 House에 count 0으로 존재하면, 그냥 그 count만 늘려서 다시 생성해주는 식으로... 또는 0이라도 그냥 서버에서 response에 그대로 포함하고, 삭제를 count=0 으로 설정하던 것을 정말 찐 삭제해버리는 방법도 있을 듯.

2020-10-18 17:44 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
> +  increase: (houseId: number, necessityId: number, count: number): void => dispatch(
오 알겠습니다 그러면 onCountHouseNecessity 안에 increase, decrease 두 개가 들어가는 구조겠군요

2020-10-18 17:44 UTC, davin111 commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
> +  increase: (houseId: number, necessityId: number, count: number): void => dispatch(
? ㄴㄴ 그냥 increase, decrease 개념 자체가 필요 없는 거 같은데.

2020-10-18 17:45 UTC, davin111 commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
> +  increase: (houseId: number, necessityId: number, count: number): void => dispatch(
걍 완전 똑같은 동작을 props로 세 번이나 정의하고 있잖어, 이미 이걸 increase할지 decrease할지는 위에서 +1, -1 하는 걸로 의미가 다했는데

2020-10-18 17:46 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityList/NecessityList.tsx
> +          <div className="necessity-item-block">
아 이거 td 쓰면 warning 문구가 계속 떠서 그냥 바꾸었습니다. 반대로 NecessityCounter에서는 아직 안바꾼 것을 볼 수 있는데, 지금의 상황은 td -> div 했을 때 외관상 아무런 변화가 없기 때문이고, NecessityCounter의 경우는 가로로 따다닥 붙는 것이 아니라 세로로 이쁘게 렌더링되기 때문에 진섭이의 css를 기다리겠습니다.

2020-10-18 17:47 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
>    create: (
서버 쪽에 다 NecessityHouse로 맞춰져있으니 하나로 통일하는 게 낫지 않을까 싶은...

2020-10-18 17:50 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
>    create: (
넹 확인했습니다.

2020-10-18 17:50 UTC, YeonghyeonKO commented on orange/src/containers/NecessityPage/NecessityPage.tsx
> +  onGetNecessity: (houseId: number): void => dispatch(
수정했습니다.

2020-10-18 17:53 UTC, davin111 commented
근데 사실 이 PR, 완전히 #53 에 dependent한 거죠? 저기서 생성한 API에 의존해서 프론트 짠거니까... 이런 경우에 확실히 명시가 있어야 하고, 요번엔 저 PR은 만나서 있을 때 작업한 거니까 괜찮지만 다른 상황에서는 저 내용을 바꿔야 할 수도 있는 거니까, 요렇게 동시 진행하는 것은 조금 리스크가 있긴 한듯. 요번 같은 것에는 좋은 효율이었던 거 같지만!

2020-10-19 02:17 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
> +  increase: (houseId: number, necessityId: number, count: number): void => dispatch(
넹 생각해보니 아예 똑같네요 다른 pr에서 반영하겠습니다!

2020-10-19 02:52 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
> +  counter: (houseId: number, necessityId: number, count: number): void => dispatch(
그냥 통일했습니다

2020-10-19 02:54 UTC, YeonghyeonKO commented
네 #54 자체는 먼저 진행했었는데, 중간에 #53을 먼저 작업해서 바로바로 반영하고 있습니다... 사실 우선순위가 끝나면 하는게 맞겠네요

2020-10-19 02:57 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
네네 min1로 두면 count에 대한 임시방편이 되어서 좋군요

2020-10-19 03:31 UTC, YeonghyeonKO reviewed
지금은 #53 이 반영되지 않았기 때문에 Counter, Remove가 Create처럼 잘 동작하지 않습니다. 
그 이유는 serializer가 달라 create 시 /api/v1/house/1/necessity/로 오는 것이 counter, remove 시에는 /api/v1/house/undefined/necessity/10 과 같이 {house_id}가 인식되지 않기 때문입니다.
해결 방안으로 제가 #53에서 house_id를 necessity body에 추가하는 경우가 있을거고 아니면 serializer 자체를 다르게 주는 방법이 있을 것 같습니다.

2020-10-19 03:31 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
흠 min="1" step="1" 설정했을 때 옆에 자동으로 생성되는 작은 증감 버튼에서만 적용되고 직접 숫자를 입력해버리면 1이 아닌 0도 입력이 되네요... parseInt 대신 parseFloat을 사용한 이유는 parseInt를 써버리면 1.3을 입력할 때 자동으로 1로 내림되어 버려서 지금으로서는 backend 로직을 사용하고자 했습니다.
<img width="770" alt="image" src="https://user-images.githubusercontent.com/46114393/96398138-1072e100-1206-11eb-81ab-176a6bfb5445.png">

2020-10-20 13:07 UTC, JSKeum commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
>    me: any;
요런 any 녀석들 제거 작업을 곧 하겠습니다

2020-10-20 13:07 UTC, JSKeum commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +    this.props.onCreateNecessityHouse(
void 타입 명시 안해도 되지 않나요?

2020-10-20 13:07 UTC, JSKeum commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
NecessityCounter를 개별 컴포넌트로 관리할 필요는 없는 것 같습니다. 지금 합치기 힘들다면 리팩토링 진행할 때 NecessityItem에 다 넣어 버립시다.

2020-10-20 13:38 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
아 지금 합치는 부분은 ON-11에서 어느정도 작업해두었기 때문에 이거 머지되면 바로 올릴 예정입니다 (다만 생필품 사라지는건 해결안됨)

2020-10-20 13:38 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +    this.props.onCreateNecessityHouse(
이거 회원가입 모달 베낀거라...

2020-10-20 13:39 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
>    me: any;
좋아용

2020-10-20 13:39 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCounter/NecessityCounter.tsx
>          <td>
반영하겠습니다

2020-10-20 15:04 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
@YeonghyeonKO 애초에 입력창에 int만 들어가게 할 수는 없을까? 그런데 그걸 떠나, 내림 되는 게 뭐가 문제이지, 어차피 뭐든 int로 입력되게 하면 되는 거니까 좋은 거 아닌가?

2020-10-20 15:05 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +    this.props.onCreateNecessityHouse(
이게 무슨 대답이야 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ @YeonghyeonKO

2020-10-20 15:08 UTC, davin111 commented
@YeonghyeonKO https://github.com/gongmyeong-study/orangenongjang/pull/54#pullrequestreview-511389933 요거 한 번 더 설명해줄 수 있을까요? 나의 https://github.com/gongmyeong-study/orangenongjang/pull/53#discussion_r508587218 이 질문과 관련 있나 싶기도 하구.

2020-10-20 16:31 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
@davin111 입력 시에 바로 소수점이 안찍히게 하는 방법은 찾아봤는데 잘 모르겠고 내림되는건 차라리 alert를 띄우는게 낫지 않을까요

2020-10-21 08:12 UTC, JSKeum commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +    this.props.onCreateNecessityHouse(
회원가입도 리팩토링 대상이라..

2020-10-21 08:13 UTC, JSKeum commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +    this.props.onCreateNecessityHouse(
우리 eslint에 타입스크립트 설정도 들어있나요?

2020-10-21 08:13 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +    this.props.onCreateNecessityHouse(
그러면 이거 type 관련해서 수정 pr 올릴 때 다 기록해놨다가 해야겠네요

2020-10-21 15:45 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
음 샤워하다가 생각한건데 내림되는 것도 좋을 것 같네요 ㅋㅋㅋ 아니면 어떤 유저는 소수점으로 개수(바나나 반개까지 기록하는 분이 있기에...) 또는 금액(물론 지금은 frontend에서 금액 뒤에 "원"이라고 표기하지만 달러화 표시할 때를 생각하면 cent도 있으므로)을 입력할 수 도 있기 때문에 float 그 자체로 backend에 넘기고 backend에서 integer만 받는 로직을 완화해도 나쁘지 않다고 봅니다.

2020-10-21 15:47 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
count의 정의는 개수니까 정수만 받아야 한다고 생각합니다.

2020-10-21 15:51 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
네 알겠습니당 그러면 다빈은 백엔드까지 양의 실수값을 넘겨주어서 정수인지 아닌지 체크해서 alert 주는 것보다는 프론트에서 양의 실수값을 입력하면 분수, 소수, 자연수에 상관없이 자연수로 내림하는 방안이 더 괜찮다는거죠??

2020-10-21 15:52 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
넵 개수니까요 그게 자연스러운 거 같아요 애초에 정수가 아닌 실수를 넣으면 '틀린' 상황 같아요

2020-10-21 15:54 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
네네 알겠습니다. 다만 '틀린' 상황이라고 생각하니깐 정수 값을 입력하라고 메시지를 띄울 것인지 아니면 '틀린' 값을 넣어도 알아서 정수로 내림할 건지는 합의가 필요할 것 같습니다!

2020-10-21 15:55 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +              onChange={(e) => this.setState({ price: parseFloat(e.target.value) })}
애초에 실수가 입력이 안 되게 하는 방안도 있을 거 같아요. 그리고 어차피 confirm이 따로 있는데 alert 띄울 필요 없지 않을까 생각합니다.

2020-10-22 13:54 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +                  ? parseFloat(e.target.value) : NaN,
`(condition) ? true : false` 를 활용해보았습니다.

2020-10-22 21:29 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateModal/NecessityCreateModal.tsx
> +                  ? parseFloat(e.target.value) : NaN,
NaN을 직접적으로 사용했군요, 신기

2020-10-22 21:34 UTC, davin111 approved these changes
일단 https://github.com/gongmyeong-study/orangenongjang/pull/54#issuecomment-711326074 관련해서는 min="1" 방식으로 0 초과로 입력하게 한 거지? 이렇게 일단 가면 될듯 이 PR에선.

2020-10-22 23:22 UTC, merged