ON-8 [back] Ordering for NecessityList & NecessityLog API
gongmyeong-study/orangenongjang pull request #55
Opened 2020-10-25 08:42 UTC by YeonghyeonKO

## Major Changes [ON-8](https://orangenongjang.atlassian.net/browse/ON-8)
#### 1. NecessityLog 생성
- [GET] `/api/v1/house/{house_id}/necessity_log/ `
- 생필품 수량 변경 시 Log 생성
- NecessityLog 정렬 방식에 기존의 '최신순'에 '사용자순'을 추가하여 사용자의 이름을 오름차순으로 하여 생필품 관리 기록을 확인 가능.

<br>

#### 2. Necessity 조회
- [GET] `/api/v1/house/{houseId}/necessity/`
- 생필품 나열 순서를 기존의 '변경순'에서 '최신순', '이름순'으로 변경함.
 
<br>

### Related Tasks
- [ON-9](https://orangenongjang.atlassian.net/browse/ON-9) 바로 작업 시작할 예정.

2020-10-26 14:39 UTC, davin111 requested changes

2020-10-26 14:39 UTC, davin111 commented on nongjang/house/serializers.py
> +        order = self.context['request'].query_params.get('order')
HouseSerializer가 쓰이는(앞으로 쓰일 수 있는) 다른 모든 API에서도 이 로직을 공통적으로 적용하고 싶어서 serializer 내에 query_param에 의존하는 로직을 얻은 거야? 예를 들어 이 Serializer를 다른 API에서 사용할 때, query param으로 order를 받을 것을 고려 안 하고 사용하면 order는 None이 되고, 아래에서 항상 else를 타겠네? 여기까지 생각하고 의도한 거 맞지?

그렇다면 일단 괜찮은데, 다만 view에 많이 가까운 query param에 의존하는 로직을 serializer에 넣는 게 좋을지는 정답이 없겠지만 조금 고민되긴 해. 일단은 OK.

2020-10-26 14:39 UTC, davin111 commented on nongjang/house/views.py
> +        log_order = self.request.GET.get('order', None)
DRF의 https://www.django-rest-framework.org/api-guide/requests/#query_params 에 따라, request.query_params를 쓰기를 권장. 그리고 get()의 두 번째 인자로 None은 필요 없음.

2020-10-26 14:39 UTC, davin111 commented on nongjang/house/views.py
> +        NecessityLog.objects.create(action='COUNT', necessity_house_id=necessity_house.id, user_id=user.id)
직접 작성한 str 대신 NecessityLog.COUNT 를 사용하자. 현 264행 참고. 가급적 인자 순서도 맞춰주면 예쁘지 않을지. 그리고 굳이 'id'에 .id를 넣으려고 할 필요 없음. 마찬가지로 264행 참고. 항상 기존 코드 참고하기.

2020-10-26 14:39 UTC, davin111 commented on nongjang/house/serializers.py
> +        order = self.context['request'].query_params.get('order')
그런데, HouseSerializer이고 기본적으로 'House'에 대한 View인데, 'order'라는 범용적으로 느껴지는 이름의 query param이 막상 Necessity의 ordering을 결정한다는 것이 좀 깨는 느낌. necessity_order로 하면 어떨지. 사실 기본 기능이 덜 된 지금으로서는 약간 오버스펙이라는 생각도 들긴 하고.

2020-10-26 14:39 UTC, davin111 commented on nongjang/house/views.py
> +            logs = NecessityLog.objects.filter(
너무 코드에 중복이 많은데,

queryset = NecessityLog.objects.filter(necessity_house__house=house).select_related('necessity_house')

으로 공통적인 부분 앞에서 빼놓고 chaining하는 게 맞을 거 같은데.

2020-10-26 14:39 UTC, davin111 commented on nongjang/house/views.py
> +                necessity_house__house=house).order_by('user_id', '-created_at').select_related('necessity_house')
username도 아닌 user_id로 정렬하는 것은 사용자 입장에서 거의 의미가 없지 않을까.

2020-10-26 14:41 UTC, davin111 commented
요번엔 '기획'에 대한 코멘트나 반대 의견 같은 것도 있었던 거 같은데, 앞으로는 조금씩 매주/격주 정도로 구현하고자 하는 내용에 대한 기획 사항을 먼저 합의하고 진행하는 것도 좋겠다는 생각이 듦.

2020-10-26 14:58 UTC, davin111 commented on nongjang/house/views.py
> +        NecessityLog.objects.create(action='COUNT', necessity_house_id=necessity_house.id, user_id=user.id)
덧붙여, 사실 PUT /api/v1/house/{house_id}/necessity/{necessity_id}/ 에서도 count가 수정될 수 있다고 생각했던 거 같은데, 내가 애초에 #48 에서 서버 많이 고칠 때부터 count 수정 로직은 해당 API(정확히는 necessity_house_id 받던 API)에서부터 그걸 안 넣긴 했군. 일단 안 넣고 그대로 가는 거 오케이. 만약 count를 해당 API에서도 수정할 수 있었다면, 그 로그를 처리하는 것에 대해서도 인지는 해두고 있어야 한다고 언급하려고 했음. 이전에 얼핏 오프라인으로 얘기했듯이.

2020-10-26 17:30 UTC, YeonghyeonKO reviewed
@davin111 review 감사합니다!

2020-10-26 17:30 UTC, YeonghyeonKO commented on nongjang/house/serializers.py
> +        order = self.context['request'].query_params.get('order')
네 Serializer가 다른 API에서 사용될 때 else 타는 것은 알고 있는데, 굳이 views.py에 넣지 않고 serializers.py에 넣은 까닭은 기존 코드가 serializers.py에서 자동으로 '-updated_at' 순으로 정렬해주고 있었기 때문입니다.

만약 Get이 아닌 다른 API에서 사용된다고 했을 때, 불필요하게 query param이 무엇인지 분기를 매번 타는 것이 별로라면 아예 views.py 쪽으로 넘겨보겠습니다. 그게 아니라면 order -> necessity_order는 좋은 의견이라 serializers.py에 반영하겠습니다.

2020-10-26 17:30 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +        log_order = self.request.GET.get('order', None)
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/46114393/97204250-36e1df00-17f9-11eb-9a4c-9ce9b3eaace2.png">
오 그렇군요 반영하겠습니다.

2020-10-26 17:30 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +                necessity_house__house=house).order_by('user_id', '-created_at').select_related('necessity_house')
저는 최신순 / 생성순 / 유저순 이렇게 세 개의 정렬 순서를 버튼으로 보여주려고 했는데 다빈은 최신순과 생성순을 토글하는 하나의 버튼을 생각한 건가요?? 나중에 필터를 건다면 거기에 사용자순을 추가하는 것은 찬성입니다!

2020-10-26 17:30 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +            logs = NecessityLog.objects.filter(
넵 앞으로 이런거에도 신경 써야겠습니다.

2020-10-26 23:41 UTC, davin111 commented on nongjang/house/views.py
> +                necessity_house__house=house).order_by('user_id', '-created_at').select_related('necessity_house')
UI는 어떻게 되든간에(근데 각각 별개의 버튼으로 있는 게 의미가 있나? 어차피 case는 세 개로 분기타는데), 사실 id라는 것은 지극히 내부적인 것이고 유저에게 노출될 일도 없는 것인데(그나마의 의미라면 생성 순서 정도), 이것을 기준으로 정렬하는 게 의미가 없다는 것이었음. 굳이 따지자면 유저의 회원가입순으로 내 집의 생필품 로그를 정렬, 같은 기능이니까. 그래서 그나마 유저순으로 정렬할 거면 username순이어야 하지 않나인데, 이것조차 로그를 이 유저에 대한 것만 보기, 같은 기능도 아니고 정렬을 하는 게 의미가 거의 없을 거 같다는 이야기.

2020-10-26 23:43 UTC, davin111 commented on nongjang/house/views.py
> +                necessity_house__house=house).order_by('user_id', '-created_at').select_related('necessity_house')
별개로 지금 상황에서 index를 추가할 필요까지는 없다고 생각하지만. 이런 인지는 하고 있어야함. 

log table은 기본적으로 row가 매우 많은 게 일반적인데, column 두 개로 order by 걸고 이에 대한 composite index가 없으면, DB 킬스위치급 쿼리가 될 가능성이 있음.

2020-10-26 23:44 UTC, davin111 approved these changes

2020-10-27 02:06 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +                necessity_house__house=house).order_by('user_id', '-created_at').select_related('necessity_house')
아하 네 알겠습니다. 처음 의도는 회원가입한 유저 순서로 배열해보면 누가 뭘 했는지 시간순으로 한 눈에 볼 수 있으니깐 편하지않을까? 였는데 나중에 차라리 필터링 기능을 넣는게 더 나아보입니다. 그러면 일단 user에 대한 order는 빼는걸로 합시다

2020-10-27 02:10 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +                necessity_house__house=house).order_by('user_id', '-created_at').select_related('necessity_house')
@davin111 딱 elif 부분만 날려서 커밋했는데, 수정사항이 괜찮으면 진섭이도 조금만 더 기다려보고 merge 하겠습니다.

2020-10-27 16:23 UTC, merged