[ON-7] Necessity Update Modal 기능 추가
gongmyeong-study/orangenongjang pull request #57
Opened 2020-11-01 13:41 UTC by YeonghyeonKO

## Major Changes [ON-7](https://orangenongjang.atlassian.net/browse/ON-7)
### 0. 개요
- [ON-13](#48 )에서 생필품 생성 시 NecessityUser table로 관리하던 기존의 방식에서 NecessityHouse table에 저장하는 것으로 바꾸었습니다. 기존 배포판에서는 회원가입 및 로그인까지 작동되는 상태에서 더 나아가 클라이언트에서의 **생필품 생성 및 수정, 수량 증감, 그리고 타임라인** 기능을 구현한 상태였기 때문에 [ON-19](#54) 및 [ON-26](#56)에서 [ON-13](#48 )의 새로운 API를 **웹 프론트**에 반영한 바 있습니다.

- 이번 PR은 이전 API를 바탕으로 생성된 **생필품을 수정**하는 API를 웹 프론트에서 **Modal**을 띄워 구현할 수 있도록 작업하던 [ON-7](https://orangenongjang.atlassian.net/browse/ON-7)을 새로운 API에 맞도록 수정 및 개선한 것입니다.

<br>

### 1. 생필품 수정 프론트엔드 작업
- NecessityCreateModal에 맞추어 비슷한 css에 **darksalmon color**(#e9967a)를 적용한 NecessityUpdateModal을 구현했습니다.
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/46114393/97804362-b3117200-1c92-11eb-96a8-cc77d9755a8d.png">

- 기존 논의에 따라 생필품 수정 시에는 생필품명과 옵션을 바꿀 수 없기 때문에 (바꾸고자 한다면 삭제를 권유) 생필품(Necessity) 및 옵션(Option)에 대한 input 태그에는 사용자가 입력할 수 없도록 **disabled** 처리하였습니다.

<br>

### 2. 생필품 수정 백엔드 작업
- 대규모 리팩토링 작업이었던 [ON-20](#48)에 맞추어 Frontend 코드를 수정하였습니다. 다만 이번 Necessity Update Modal에서 [가격을 수정할 시 else문이 분기를 잘못타는 것을 수정](nongjang/house/views.py)하였습니다.

<br>

## Minor Changes
- createNecessity, removeNecessity, countNecessity 함수의 이름을 각각 createNecessityHouse, removeNecessityHouse, countNecessityHouse로 수정한 것에 맞추어 **updateNecessity 역시 updateNecessityHouse로 함수를 명명**하였습니다.

- Props에서 타입을 지정해주는 함수의 경우 "on"을 함수명 앞에 붙였습니다. 

<br>

## What to do Next
- [ON-11](#47), [ON-19](#54)과 더불어 Necessity 수정 성공 시 map으로 necessities array가 들어오지 않고 단일 necessity만 들어와 렌더링되지 않는 현상을 해결할 예정입니다.(Assignee : @JSKeum )

<br>

2020-11-04 06:23 UTC, JSKeum requested changes

2020-11-04 06:23 UTC, JSKeum commented on nongjang/house/views.py
>          else:
앞으로 validation은 serializer에서 하는 건 어떨까요?

2020-11-04 06:23 UTC, JSKeum commented on orange/src/components/Necessity/NecessityItem/NecessityItem.tsx
> +function NecessityItem(props: Props): ReactElement {
ReactElement 선언이 필요한가요?

2020-11-04 06:23 UTC, JSKeum commented on orange/src/components/Necessity/NecessityUpdateModal/NecessityUpdateModal.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(NecessityUpdateModal);
update 모달이랑 create 모달은 한 컴포넌트로 관리하면 좋지 않을까요?

2020-11-04 06:23 UTC, JSKeum commented on orange/src/store/actions/necessity/necessity.tsx
> +  .catch((updateError) => dispatch(updateFailure(updateError)));
ON-16이랑 머지 충돌이 예상됩니다ㅎㅎ 나중에 머지되는 사람이 잘 하기!

2020-11-04 07:11 UTC, YeonghyeonKO commented on nongjang/house/views.py
>          else:
넵 지금은 front 작업 하다가 발견한 작은 문제였어서 django 코드도 수정했던건데 나중에 serializer로의 리팩토링을 고려해봐야겠군요

2020-11-04 07:12 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityUpdateModal/NecessityUpdateModal.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(NecessityUpdateModal);
NecessityModal 내부에 create, update function을 넣자는 말인가요?

2020-11-04 07:27 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityItem/NecessityItem.tsx
> +function NecessityItem(props: Props): ReactElement {
필요없나보네요. 다른 코드지만 아래 사진 src/App.tsx 15번째 줄의 JSX.Element 호출은 꼭 필요한건가요?
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/46114393/98081482-850e7680-1eba-11eb-8590-efdb971509ff.png">

2020-11-04 07:50 UTC, JSKeum commented on orange/src/components/Necessity/NecessityUpdateModal/NecessityUpdateModal.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(NecessityUpdateModal);
네 두 컴포넌트의 기능이 거의 같은 것 같으니 하나로 만들고, dispatch만 다르게 하는게 좋지 않을까요? 그리고 update에서도 count, price, option까지 모두다 수정 가능하게 하는게 낫지 않을까요?

2020-11-04 07:56 UTC, JSKeum commented on orange/src/components/Necessity/NecessityItem/NecessityItem.tsx
> +function NecessityItem(props: Props): ReactElement {
: JSX.Element는 리턴 타입을 명시하는건데, 필요 없을 것 같습니다.

2020-11-04 08:04 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityUpdateModal/NecessityUpdateModal.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(NecessityUpdateModal);
넵 반영하도록 하겠습니다

2020-11-04 11:30 UTC, davin111 commented on nongjang/house/views.py
>          else:
나도 그렇게 추후 수정하는 게 좋다고 생각함. 이 PR에서는 아니고. 암튼 이쪽 코드가 제법 끔찍하긴 하구만. 내가 서버 코드 #48 에서 대거 고칠 때 그렇게 하는 게 좋겠다고 생각했는데, 일단 기능적 로직 리팩토링만 하기에도 변화량이 너무 많아서 일부러 코드를 예쁘게 하는 리팩토링은 수행하지 않았음. serializer를 이용해 price, count 등의 request body를 validation하고 model create까지 하도록 수정하는 별도의 backend task JIRA 카드를 생성해두면 좋을 듯. @JSKeum @YeonghyeonKO

2020-11-05 01:18 UTC, YeonghyeonKO commented on orange/src/store/actions/necessity/necessity.tsx
> +  .catch((updateError) => dispatch(updateFailure(updateError)));
@JSKeum 아무래도 진섭이꺼 먼저 merge될 것 같으니 머지되면 최대한 잘.... 제꺼 바꿔보도록 하겠습니다

2020-11-08 06:49 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityUpdateModal/NecessityUpdateModal.tsx
> +  }
이 부분 없앤 버젼으로 commit 했는데 file changed에는 남아있네요 뭐지

2020-11-08 06:49 UTC, YeonghyeonKO commented on orange/src/store/reducers/necessity/necessity.tsx
>      const indexToBeUpdated = necessityHouse.necessities.findIndex(({ id }) => id === data.id);
**action.type**이 COUNT_SUCCESS, REMOVE_SUCCESS, UPDATE_SUCCESS인 경우를 **SingleResponseCases**로 한꺼번에 묶어 처리하도록 했습니다.

2020-11-11 00:50 UTC, JSKeum commented on orange/src/components/Necessity/NecessityUpdateModal/NecessityUpdateModal.tsx
> +  }
console.log 다시 지워주세요!

2020-11-11 00:50 UTC, JSKeum commented on orange/src/components/Necessity/NecessityUpdateModal/NecessityUpdateModal.tsx
> +export default NecessityUpdateModal;
이 update form도 ON-28에 material ui form 방식으로 수정하겠습니다

2020-11-11 00:50 UTC, JSKeum commented on orange/src/components/Necessity/NecessityItem/NecessityItem.tsx
> +        restoreUpdateModal();
restoreUpdateModal() 이 아니라 update api request의 결과에 따른 로직이 필요한데, 그때 redux state가 then() 안에서 동기화되지 않는 문제 때문에 임시로 이렇게 처리한 것으로 보입니다. 그럼 일단 이렇게 두고 고민을 더 해봐야 할 것 같습니다.

2020-11-15 02:19 UTC, JSKeum commented
LGTM!

2020-11-15 02:20 UTC, JSKeum approved these changes

2020-11-15 02:43 UTC, merged