ON-24 [back] House 초대장 API
gongmyeong-study/orangenongjang pull request #61
Opened 2020-11-11 03:12 UTC by YeonghyeonKO

## Major Changes [JIRA ON-24](https://orangenongjang.atlassian.net/browse/ON-24)
**1. House 초대장 기능**
- secret_info.json을 다음과 같이 수정합니다. (현재는 개인 이메일로 구동되는 것을 확인했습니다.)
```
{
    "DATABASE_NAME": "{database_name}",
    "DATABASE_USER": "{database_user}",
    "DATABASE_PASSWORD": "{database_password}",
    "DATABASE_HOST": "{database_host}",
    "DATABASE_PORT": "3306",
    "EMAIL_BACKEND" : "django.core.mail.backends.smtp.EmailBackend",
    "EMAIL_HOST" : "smtp.gmail.com",
    "EMAIL_PORT" : "587",
    "EMAIL_HOST_USER" : "{email_host_user}", # admin@orangenongjang.com과 같은 형태
    "EMAIL_HOST_PASSWORD" : "{email_host_password}", # admin@orangenongjang.com 비밀번호
    "SERVER_EMAIL" : "{server_email}", # admin@orangenongjang.com과 같음.
    "DEFAULT_FROM_MAIL" : "{default_from_mail}" # admin@orangenongjang.com과 같음.
}
```

- House leader로 하여금 초대받기를 원하는 다른 user가 등록한 Email을 입력시 House 초대 메일을 보냄.
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/46114393/98759589-ba641880-2414-11eb-82d2-6caf53aa6a7a.png">

<br>

- 회원가입한 User 테이블을 조회하여 leader가 입력한 Email이 존재하지 않을 시 400 에러를 반환
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/46114393/98759612-c6e87100-2414-11eb-833c-7edb33e8c2fa.png">

<br>

- 메일 전송에 성공했을 시 아래와 같이 메일이 전송됨.
<img width="1718" alt="image" src="https://user-images.githubusercontent.com/46114393/98759039-8a684580-2413-11eb-8b72-58a21d2fafe3.png">

<br>
<br>

## What to do Next
1. [ON-35](https://orangenongjang.atlassian.net/browse/ON-35)를 통해 User App 리팩토링 단행
2. orangenongjang 전용 EMAIL 생성 (gmail로 생성하려고 시도했는데 여러 제약이 있어 포기함)

<br>

#### 참고
- https://velog.io/@snowman39/Django-에서-이메일-보내기-SMT-Gmail-API
- https://docs.djangoproject.com/en/3.1/topics/email/

2020-11-11 03:23 UTC, YeonghyeonKO commented
한 가지 깨달은건데 제가 현재 PR 중인 ON-7 branch를 따서 작업해버렸네요.. 다음부터는 이러는 일 없이 최신 상태의 main branch에서 작업하도록 하겠습니다.

2020-11-11 04:33 UTC, YeonghyeonKO reviewed
ON-24 PR 에서 Files changed에 해당하는 파일은
**nongjang/house/views.py**과 **nongjang/nongjang/settings.py**입니다.

2020-11-14 03:04 UTC, davin111 requested changes
오... 나도 Django에 Email 관련해 이런 식으로 직접 개발해본 적은 없는데 흥미롭네. 기본적으로 믿을 수밖에 없을 거 같고, 일단 새로 만든 POST /api/v1/house/{house_id}/invitation/ 에 대해서 내가 단 코멘트 위주로 반영하면 좋을 듯. 그리고 @YeonghyeonKO 이 직접 위에서 말했듯, 이 PR이 #57 PR branch에서 그대로 checkout 한 거라서 쓸데없는 diff가 많고, 절대 이 PR이 #57 보다 먼저 merge되면 안 될듯. 이건 좀 치명적인 아쉬움이긴 함!

2020-11-14 03:04 UTC, davin111 commented on nongjang/nongjang/settings.py
> +        # Django Mail
TEST 환경에서는 이걸 어떻게 하지? 라는 고민도 필요할 수는 있을 듯.

2020-11-14 03:04 UTC, davin111 commented on nongjang/house/views.py
> +        # Serializer를 통해 올바른 email 형식인지 검증할 필요가 있음. 현재 user에 대한 validation(email 형식 등) 로직이 없어 리팩토링해야 함.
요런 거 `# FIXME: ` 같은 식으로 주석 달아주면 IDE에서 더 눈에 띄게 잘 표시됩니다.

2020-11-14 03:04 UTC, davin111 commented on nongjang/house/views.py
> +            return Response({'error': "Email 주소를 입력해주세요."}, status=status.HTTP_404_NOT_FOUND)
그리고 email이 None인지 체크하는 것은, `if not User.objects.filter(email=email).exists():`보다 위에 들어가야할듯. 그냥 400 줄만한 것은 API의 가장 위에서? 그렇지 않으면 어차피 못 동작할 API가 DB에 쓸데없이 query를 하는 시간이 걸림.

2020-11-14 03:04 UTC, davin111 commented on nongjang/house/views.py
> +        EmailMessage(subject, message, to=[email]).send()
뭔가 send()를 못하는 상황이 있을 거 같은데 여러 문제로(세상에 존재하지 않는 이메일이거나, 순간적으로 인터넷 상황이 안좋거나 등), 그럴 때 발생하는 Exception 찾아서 except 처리하는 로직이 있어야할 듯. 그리고 그 경우에도 사용자에게 알려줘야할 것이고.

2020-11-14 05:16 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +        # Serializer를 통해 올바른 email 형식인지 검증할 필요가 있음. 현재 user에 대한 validation(email 형식 등) 로직이 없어 리팩토링해야 함.
@davin111 현재 serializers.py에 reponse로 무엇을 줄 것인지 정의하는거 빼곤 아무런 validation이 없어 다음과 같이 회원가입이 가능한 상태야. 그래서 [Jira ON-35](https://orangenongjang.atlassian.net/browse/ON-35)를 만들었는데 이에 대한 의견도 궁금하오
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/46114393/99140296-e89b5f80-2683-11eb-8ca3-00ed5923ee77.png">

2020-11-14 05:16 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +            return Response({'error': "Email 주소를 입력해주세요."}, status=status.HTTP_404_NOT_FOUND)
아 넴 좋습니다!

2020-11-14 05:19 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +            return Response({'error': "등록되지 않은 Email입니다."}, status=status.HTTP_400_BAD_REQUEST)
response 단에서 필요한게 없으면 (email을 적지 않는 경우) 보통 400을 쓰는건가

2020-11-14 05:22 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +            return Response({'error': "leader이므로 집을 떠날 수 없습니다. leader를 다른 유저에게 양도한 뒤 다시 시도해 주세요"},
좋네요 앞으로 메시지 내용이나 에러 내용은 다 쌍따옴표로 가겠습니다. 나머지는 그냥 따옴표

2020-11-14 05:34 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +        # Serializer를 통해 올바른 email 형식인지 검증할 필요가 있음. 현재 user에 대한 validation(email 형식 등) 로직이 없어 리팩토링해야 함.
오 꿀팁이군요

2020-11-14 05:35 UTC, davin111 commented on nongjang/house/views.py
> +            return Response({'error': "등록되지 않은 Email입니다."}, status=status.HTTP_400_BAD_REQUEST)
그렇지. 이 경우는 '필요한 게 없는 경우'는 물론 아님. 일단 email 형식은 제대로 받았다는 전제 하에(그래서 email 존재부터 체크하는 로직이 선행되어야 한다는 거고) DB를 뒤졌는데 없다는 거니까 404도 괜찮을 수 있다는 것이고.

2020-11-14 05:36 UTC, YeonghyeonKO commented on nongjang/nongjang/settings.py
> +        # Django Mail
음 그렇네요 TEST할 때 Django Mailing 까지 확인해보자는 건가요 아니면 현재 코드대로라면 test할 때 분기를 django mail까지 타게되니 에러가 날 것 같다는 뜻인가요??

2020-11-14 05:38 UTC, davin111 commented on nongjang/house/views.py
> +        # Serializer를 통해 올바른 email 형식인지 검증할 필요가 있음. 현재 user에 대한 validation(email 형식 등) 로직이 없어 리팩토링해야 함.
음 그러니까 그건 알고 있는데, email이 EmailField 일 거라서 ModelSerializer 통해 Save하기만 하면 알아서 validation 될 거라는 얘기였어. 그러니까 https://orangenongjang.atlassian.net/browse/ON-35 이 그런 방식으로 고치겠다는 거라면 좋다고 생각.

2020-11-14 05:41 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +            return Response({'error': "등록되지 않은 Email입니다."}, status=status.HTTP_400_BAD_REQUEST)
아하 저는 User에서 email 뒤져서 없는 경우의 status는 404로 가겠습니다 (개인취향)

2020-11-14 06:13 UTC, YeonghyeonKO commented on nongjang/nongjang/settings.py
> +        # Django Mail
<img width="846" alt="image" src="https://user-images.githubusercontent.com/46114393/99141168-dfae8c00-268b-11eb-994e-08a574bf9b29.png">

참고 : https://blog.mailtrap.io/django-send-email/

나중에 여기 참고해야지

2020-11-14 06:14 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +        EmailMessage(subject, message, to=[email]).send()
<img width="839" alt="image" src="https://user-images.githubusercontent.com/46114393/99141089-b5100380-268a-11eb-999e-c1d4d396ed8b.png">

이 예외들에 대해서 수정해봤습니다.

2020-11-14 06:15 UTC, davin111 commented on nongjang/nongjang/settings.py
> +        # Django Mail
둘 다 생각했어

2020-11-14 06:17 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +        EmailMessage(subject, message, to=[email]).send()
`with mail.get_connection() as connection:`를 로직에 넣어봤는데 이게 인터넷 환경을 보장하는지는 확인을 못했습니다 ㅠㅠ

2020-11-14 06:19 UTC, YeonghyeonKO reviewed
ON-7이랑 섞이니깐 끔찍하군요

2020-11-14 06:19 UTC, YeonghyeonKO commented on nongjang/nongjang/settings.py
> +        # Django Mail
넴 위 Test로 확인 가능할듯

2020-11-14 06:43 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +        # Serializer를 통해 올바른 email 형식인지 검증할 필요가 있음. 현재 user에 대한 validation(email 형식 등) 로직이 없어 리팩토링해야 함.
아아 알겠습니다. 염두에 두겠습니당 내일 당장 이걸 해야겠군

2020-11-14 08:27 UTC, davin111 approved these changes

2020-11-14 08:27 UTC, davin111 commented on nongjang/house/views.py
> +        if email is None:
이 경우에는 사실 빈 str도 포함해서 if not email: 정도도 괜찮긴 하겠다는 생각은 듦.

2020-11-14 08:27 UTC, davin111 commented on nongjang/house/views.py
> +            except SMTPRecipientsRefused:
SMTPException 으로 넓게 잡아도 좋지 않을까?

2020-11-15 01:42 UTC, JSKeum commented
훌륭합니다!

2020-11-15 02:51 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +        if email is None:
반영

2020-11-15 02:51 UTC, YeonghyeonKO commented on nongjang/house/views.py
> +            except SMTPRecipientsRefused:
반영

2020-11-15 02:52 UTC, merged