[back] ON-35 Serializer를 통한 User validation 및 User 회원가입 시 인증 API
gongmyeong-study/orangenongjang pull request #64
Opened 2020-11-16 06:08 UTC by YeonghyeonKO

2020-11-16 14:49 UTC, davin111 commented on nongjang/user/views.py
> +            user = User.objects.get(pk=uid)
draft PR이지만 https://gongmyeongstudy.slack.com/archives/C011CSJ7YBH/p1605537657003500?thread_ts=1605506927.000100&cid=C011CSJ7YBH 여기서 안된다는 얘기를 해서 잠깐만 시간 투자해서 언뜻 보았을 때 하나 의아한 것은, User table pk는 현재 그냥 integer id일텐데 위의 방식으로 이용되는 uid로 User를 get할 수 있는 것이 맞는지?

2020-11-16 14:54 UTC, davin111 commented on nongjang/user/views.py
> +                user.is_active = True
미리 한 가지 comment 남겨두자면, is_active는 탈퇴 유저 처리할 때로 쓰고, is_verified column을 따로 만드는 게 어떨까 하는 생각은 듭니닷... 이 경우 물론 User(또는 Django가 지원하는 AbstractUser 같은 여러 추상화된 User model들) model을 상속하는 다른 model을 정의하여 migration을 새롭게 하는 게 필요하겠지만

2020-11-16 14:58 UTC, YeonghyeonKO commented on nongjang/user/views.py
> +            user = User.objects.get(pk=uid)
@davin111 urls.py에 `path('user/<str:uidb64>/activate/<str:token>', UserActivate.as_view())`로 걸어두긴 했는데 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/46114393/99267546-6a97ae00-2867-11eb-9d9c-76c0a1b8562c.png"> 이렇게 뜨는걸 보니 API 자체가 작동이 안되는 상황 같네요

2020-11-16 14:58 UTC, YeonghyeonKO commented on nongjang/user/views.py
> +                user.is_active = True
@davin111 좋습니다 아까 Django mail (회원가입 시 인증 또는 비밀번호 reset 기능) system 관련해서 Medium 글 몇개 봤는데 다들 Custom Model 만들어서 하더군요

2020-11-16 14:59 UTC, davin111 commented on nongjang/user/views.py
> +            user = User.objects.get(pk=uid)
urls.py 부터 그럼 다시 제대로 차근차근 보는 걸로.

2020-11-16 14:59 UTC, davin111 commented on nongjang/user/views.py
> +                user.is_active = True
ㅇㅇ 근데 이거 많이 어려우면 validation 리팩토링 이슈만 따로 빼서 먼저 처리하는 것도 좋다고 생각. 아마 생각보다 어려운 점들이 더 있을 것 같아서.

2020-11-16 15:00 UTC, YeonghyeonKO commented on nongjang/user/views.py
> +                user.is_active = True
넴 방금 Jira 분리했습니다 얘는 바로 PR 올려볼게요

2020-11-17 12:56 UTC, davin111 requested changes
NO...

2020-11-17 12:56 UTC, davin111 commented on nongjang/user/serializers.py
> +        if not username or not email:
username은 애초에 필수 column이라서 애초에 blank가 원래 안 되지 않니? 자동으로 validation 될 듯. 그리고 email 같은 경우도 UserSerializer 자체적으로 required, allow_blank, allow_null 같은 것들을 이용해서 넣으면 될 듯. 특정 column 미포함은 굳이 validate() 까지 거창하게 쓸 필요 없음.

2020-11-17 12:56 UTC, davin111 commented on nongjang/user/serializers.py
> +        if User.objects.filter(email=email).exists():
email을 unique column으로 하고 싶으면 이전에 언급했듯 Django User(또는 AbstractUser 등) 상속하는 model을 파는 게 좋을 듯. 굳이 여기서 validate X. 일단 이 PR에선 넘기는 게 좋지 않을지.

2020-11-17 12:56 UTC, davin111 commented on nongjang/user/serializers.py
> +        return user
전혀 필요없는 overriding

2020-11-17 12:56 UTC, davin111 commented on nongjang/user/views.py
> +    @transaction.atomic
View function 전체에 transaction.atomic을 거는 것은 상당히 위험해서 안 하는 게 좋을듯.

2020-11-17 12:56 UTC, davin111 commented on nongjang/user/views.py
> +        except IntegrityError:  # 중복된 username or email
이거 사실 일반적으로 username 등이 중복되는 경우엔 is_valid에서 400으로 빠지는 거 알지? 너가 지금 짠 방식도 email 중복이면 try 위에서 is_valid() 할 때 400으로 빠지는 거야. 이 경우는 정말 특이 케이스로, validate 할 때에는 중복 없다가 막상 insert 하는 순간 보니까 중복되는 거 생겼을 때를 처리하는 것임. 워낙 코너 케이스니까 현재로서는 차라리 없애는 게 나을듯.

2020-11-17 13:20 UTC, YeonghyeonKO commented on nongjang/user/serializers.py
> +        if User.objects.filter(email=email).exists():
넵 Account라는 이름의 Model을 팔까 생각중입니다. (가입인증, 비밀번호 초기화에 이용하기에 더 적합한 모델) pr에서 '넘긴다'는 말은 새로운 모델 만들기 전까지 임시방편 validate를 하자는 말이죠??

2020-11-17 13:21 UTC, YeonghyeonKO commented on nongjang/user/views.py
> +    @transaction.atomic
흠 넹 오히려 '굳이'인가..

2020-11-17 13:21 UTC, YeonghyeonKO commented on nongjang/user/views.py
> +        except IntegrityError:  # 중복된 username or email
그런데 얘를 처리해주려면 transaction.atomic을 사용하면 되지 않을까요?

2020-11-17 15:08 UTC, YeonghyeonKO commented on nongjang/user/serializers.py
> +        if not username or not email:
이 부분은 다 날려도 되는거네요. required, allow_blank, allow_null 모두 default가 각각 True, False, False라서 제가 원하는 스펙입니다.

2020-11-18 16:35 UTC, davin111 requested changes

2020-11-18 16:35 UTC, davin111 commented on nongjang/user/serializers.py
> +        user = super().create(validated_data)
이거 real로 create 자체를 overriding 하지 말란 말이었어. child의 동작이 parent와 똑같은데 재정의할 필요가 없잖아.

2020-11-18 16:35 UTC, davin111 commented on nongjang/user/serializers.py
> +        if User.objects.filter(email=email).exists():
@YeonghyeonKO 아예 그냥 중복 validation 자체를 일단 넣지 말자는 의미긴 했는데 일단 이렇게 냅둬도 괜찮기는 할듯...

2020-11-18 16:35 UTC, davin111 commented on nongjang/user/views.py
> +        except IntegrityError:  # 중복된 username or email
명확한 이해와 이유가 있지 않은 상황에서 transaction.atomic을 쓰는 것 자체가 문제적이라고 여겨짐.

2020-11-18 17:07 UTC, YeonghyeonKO commented on nongjang/user/serializers.py
> +        user = super().create(validated_data)
상속 전에 항상 부모 코드 봐야겠군요... ModelSerializer의 default 함수는 create, update인 것을...

2020-11-18 17:07 UTC, YeonghyeonKO commented on nongjang/user/serializers.py
> +        if User.objects.filter(email=email).exists():
네 일단은 이렇게 갈게요

2020-11-18 17:07 UTC, YeonghyeonKO commented on nongjang/user/views.py
> +        except IntegrityError:  # 중복된 username or email
[여기](https://lee-seul.github.io/django/2019/02/02/django-transactionmanagementerror.html) 잘 나와 있군요
transaction.atomic이 DB 입장에서 항상 나쁘지 않은 친구라고 생각했는데 try except 구문 바깥에서 사용했을 때에 대해 Django가 test까지 짜놔서 조심하라고 하는게 감동입니다...

2020-11-18 17:07 UTC, davin111 commented on nongjang/user/serializers.py
> +        user = super().create(validated_data)
아니 그것도 그건데, 걍 이건 부모 코드 안 봐도 이 두 라인 자체가 그냥 자기 반복이잖아 ㅋㅋㅋ

2020-11-18 17:08 UTC, davin111 commented on nongjang/user/serializers.py
> +        user = super().create(validated_data)
관련 Python 문법 공부 ㄱㄱ

2020-11-18 17:08 UTC, davin111 commented on nongjang/user/views.py
> +        except IntegrityError:  # 중복된 username or email
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 이거 우리 회사 서버 개발자 분 블로그네 ㅋㅋㅋㅋㅋㅋㅋ

2020-11-18 17:08 UTC, davin111 commented on nongjang/user/views.py
> +        except IntegrityError:  # 중복된 username or email
이 상황에 딱 맞는 얘기일지는 모르겠는데 암튼 뭐... 넹

2020-11-18 17:09 UTC, davin111 approved these changes

2020-11-18 17:11 UTC, YeonghyeonKO commented on nongjang/user/views.py
> +        except IntegrityError:  # 중복된 username or email
오 진짜 매스프레소 개발자 분이셨네 이분 꽤 링크드인이나 어디서 본 듯 
깃헙 블로그에 광고를 많이 다셨군

2020-11-18 17:12 UTC, merged