ON-38 [front] Timeline 예쁘게 꾸미기
gongmyeong-study/orangenongjang pull request #67
Opened 2020-11-20 19:41 UTC by YeonghyeonKO

[Jira ON-38](https://orangenongjang.atlassian.net/browse/ON-38)

## Major Changes
- `yarn add @material-ui/lab` 을 통해 lab component를 다운받았습니다. (merge시 `yarn install` 필수!)

- 단순히 necessity_log를 매핑하여 단순 텍스트로만 렌더링하던 기존과 달리 TimeLine 느낌이 들도록 각종 아이콘을 곁들여보았습니다.

![image](https://user-images.githubusercontent.com/46114393/99842171-af4a7e80-2bb2-11eb-9d31-1be0127a9842.png)

- [Jira ON-42](https://orangenongjang.atlassian.net/browse/ON-42)의 문제를 해결해야만 생필품 삭제 시 해당 생필품에 관련된 모든 액션만 남고 어떤 생필품이었는지 표출되지 않는 버그를 고칠 수 있습니다.

2020-11-20 19:44 UTC, YeonghyeonKO reviewed
오랜만에 꾸미는 웹프론트하니깐 재밌네요 ㅎㅎ

2020-11-20 19:44 UTC, YeonghyeonKO commented on orange/src/components/LogList/LogList.tsx
> +    // eslint-disable-next-line react/prop-types
예전에 진섭이가 이 주석을 왜 달았지 했던게 이해가 되었읍니다...

2020-11-20 19:44 UTC, YeonghyeonKO commented on orange/src/components/LogList/LogList.tsx
> +        return <AutorenewIcon />;
activityIcon 함수 만드는 아이디어 좋지 않습니까

2020-11-21 08:16 UTC, davin111 approved these changes
오 상당히 좋구만. material-ui 썼네. @JSKeum 의 확인 부탁.

2020-11-21 08:35 UTC, JSKeum requested changes

2020-11-21 08:35 UTC, JSKeum commented on orange/src/components/LogList/LogList.tsx
> +
makeStyles는 꼭 필요한 건가요?? 일반 class와 css로 할 수 있다면 굳이 style 모듈을 사용하지 않아도 될 것 같습니다!

2020-11-21 08:35 UTC, JSKeum commented on orange/src/components/LogList/LogList.tsx
> +    // eslint-disable-next-line react/prop-types
내가 언제 달았지?ㅋㅋㅋ

2020-11-21 08:35 UTC, JSKeum commented on orange/src/containers/TimelinePage/TimelinePage.css
> +}
padding-bottom 따로 쓰지 말고 padding에 넣어주세요! `padding: 5px 100px 5px 0`

2020-11-21 08:35 UTC, JSKeum commented on orange/src/containers/TimelinePage/TimelinePage.tsx
>        </div>
(아마도 제가 쓴 것 같은데) `{getLogStatus === necessityUserLogStatus.SUCCESS && logList}`로 쓰는게 보기 좋을 것 같습니다!

2020-11-21 08:37 UTC, JSKeum commented
material-ui 사용법 익히는데 시간 좀 걸렸을텐데 고생 많으셨어요! 멋집니다

2020-11-21 08:39 UTC, YeonghyeonKO commented on orange/src/containers/TimelinePage/TimelinePage.css
> +}
@JSKeum 진섭 그리고 이거 타임라인 좌우 너비를 탭 4개 사이즈에 맞추려고 하면 어떻게 해야할까

2020-11-21 08:39 UTC, YeonghyeonKO commented on orange/src/containers/TimelinePage/TimelinePage.tsx
>        </div>
넵 좋습니다

2020-11-21 08:45 UTC, JSKeum commented on orange/src/containers/TimelinePage/TimelinePage.css
> +}
`.timeline-page { display: flex;  justify-content: center; }` 이렇게 하면 될듯

2020-11-23 15:17 UTC, JSKeum approved these changes

2020-11-23 15:38 UTC, merged