ON-1 [front] place 추가 기능 + necessity 컴포넌트들 리팩토링
gongmyeong-study/orangenongjang pull request #70
Opened 2020-11-27 19:07 UTC by JSKeum

### Place 버튼 추가
* place 만들기 버튼 넣었습니다
* MainPage의 PlaceBox들을 carousel로 감쌌습니다. carousel은 가장 대중적인 react-slick를 사용했습니다

### Necessity 컴포넌트들 리팩토링
* necessity와 관련된 컴포넌트들이 비효율적으로 여기저기 널브러져 있는 느낌이 강해서 place를 추가하는 김에(이 상태로 place를 끼워 넣기가 힘들어서) 구조를 개편했습니다
* 리팩토링한 necessity 컴포넌트들의 계층 구조는 다음과 같습니다 
  - NecessityPage 
    - PlaceBox
      - NecessityCreateOrUpdateForm
      - NecessityList
        - NecessityItem
        - NecessityCounterButton
        - NecessityUpdateButton
        - NecessityRemoveButton
    - PlaceCreateForm
* 관심사의 분리 원칙을 지키고자 했습니다. 예를 들어 NecessityItem는 necessity를 보여주는 역할만 하고 다른 기능은 신경 쓰지 않습니다. NecessityList는 necessity 목록과 그 necessity에 종속된 UpdateButton, CounterButton 등을 드러내는 역할만 합니다. update나 counter 로직은 신경 쓰지 않습니다.
* create form에도 material ui를 도입했습니다

### Necessity 컴포넌트들 redux hook 방식으로 변경
* connect, mapStateToProps와 같은 이전 redux 방식에서 깔끔한 훅(react-redux)을 사용하는 방식으로 변경했습니다
* dispatch => useDispatch / state => useSelector

### font awesome 도입
* 모든 아이콘을 font awesome에서 가져왔습니다. font awesome은 cdn 방식으로 추가했습니다
* 웹 프론트에서 아이콘 쓸일 있으면 font awesome 강추!

*반응형 css 및 디자인 고도화는 아직입니다

<img width="956" alt="Screen Shot 2020-11-28 at 4 02 22 AM" src="https://user-images.githubusercontent.com/54926767/100478432-884df880-312e-11eb-9164-81329d4d30ae.png">

2020-11-28 00:07 UTC, YeonghyeonKO commented
@JSKeum 선생님 Button 정의해놓고 안써서 github actions failed가 떴네요

2020-11-28 02:04 UTC, JSKeum commented
> @JSKeum 선생님 Button 정의해놓고 안써서 github actions failed가 떴네요

lint 단계에서 unused import랑 variable은 자동으로 없애주면 좋겠다

2020-11-28 03:38 UTC, YeonghyeonKO requested changes
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/46114393/100493060-a0496a80-3176-11eb-9d62-39e97e5783a3.png">
@JSKeum 선생님 제 타임라인 PR은 어디로 갔습니까 ㅋㅋㅋㅋ

2020-11-28 03:38 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityList/NecessityList.css
> +  height: 5.6vw;
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/46114393/100493003-fe298280-3175-11eb-8349-8f0cfcf5bfb0.png">
현재 생필품 추가 버튼이랑 실제 생필품 item 하나하나가 같은 css의 영향을 받고 있어 스크린샷처럼 정렬이 예쁘지 않은데 추가 버튼만 따로 떼내면 쉽게 정렬할 수 있을 것 같습니다

2020-11-28 03:38 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityList/NecessityList.tsx
> +              첫 생필품을 추가해보세요!
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/46114393/100493039-6d9f7200-3176-11eb-91ff-cbb59ea968ee.png">
훌륭.... 근데 warning은 왜이리 많이 뜨지

2020-11-28 03:39 UTC, YeonghyeonKO commented
> > @JSKeum 선생님 Button 정의해놓고 안써서 github actions failed가 떴네요
> 
> lint 단계에서 unused import랑 variable은 자동으로 없애주면 좋겠다

2020-11-28 04:56 UTC, davin111 commented
왜 닫은 것...? @YeonghyeonKO

2020-11-28 04:59 UTC, davin111 commented
https://github.com/gongmyeong-study/orangenongjang/pull/70#issuecomment-735027731 @JSKeum 음 요건 `yarn lint-fix` 만들어뒀는데 이걸로 해결될 거 같기도 한데?

2020-11-28 05:00 UTC, davin111 commented
https://github.com/gongmyeong-study/orangenongjang/pull/70#pullrequestreview-540213863 @YeonghyeonKO 어디 갔냐는 게 무슨 말이야? 이해가 안 됩니다 ㅜ

2020-11-28 05:01 UTC, davin111 commented on orange/src/components/Necessity/NecessityList/NecessityList.tsx
> +              첫 생필품을 추가해보세요!
ㅠㅠ warning 안 뜨게 하면 좋긴 할 거 같아요. 이전에는 다 warning 제거 했었어서.

2020-11-28 05:07 UTC, davin111 commented on orange/src/components/Necessity/NecessityCounterButton/NecessityCounterButton.tsx
> +      <i className={`far ${props.countType === 'add' ? 'fa-plus-square' : 'fa-minus-square'} fa-2x`} />
요런 식으로 많이 합니다.

2020-11-28 05:30 UTC, davin111 requested changes
이슈 카드부터 place 추가랑 necessity 컴포넌트 리팩토링이 합쳐졌는데, 실제 작업도 오래 걸린만큼 이런 건 카드와 PR을 항상 분리시키는 것이 좋다고 생각. 그리고 나도 로컬에서 front, server 다 켜서 확인 간단히 해보기는 했는데 기존 동작 안 깨지는 것은 확실히 확인된 거지? (이제 후반부인만큼 기존 것 안 깨지는 것도 효율적인 개발을 위해 중요할 거 같아서)

몇 가지 리뷰를 꼼꼼히 해보려 했는데, 확인 부탁.

2020-11-28 05:30 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateOrUpdateForm/NecessityCreateOrUpdateForm.tsx
> +    props.placeId, props.necessityToBeUpdated!.id, data.description, data.price, data.count,
no-non-null-assertion 을 disable한 이유는 무엇?

2020-11-28 05:30 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateOrUpdateForm/NecessityCreateOrUpdateForm.tsx
> +          placeholder="크리넥스"
ㅋㅋㅋ 이제 이러한 예시 placeholder 말고 다른 진짜 내용이 들어가도 좋지 않을까 싶기도 하고.

2020-11-28 05:30 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateOrUpdateForm/NecessityCreateOrUpdateForm.tsx
> +          placeholder="부드러운거임"
![스크린샷 2020-11-28 14 18 43](https://user-images.githubusercontent.com/35535636/100494405-a2b2c100-3184-11eb-9306-a3367828c269.png)

이 부분 유저가 좀 헷갈릴 만한 것이, 내가 이름을 '세제', 옵션을 '테크'라고 적어놨고 설명은 비어있는 상황. 그런데 edit에서 변경할 수 없는 세제, 테크와 함께 '설명'이 비어있어서 보이는 placeholder인 이 내용도 똑같은 느낌으로 떠서 "내가 이런 설명을 넣었었나?" 싶은 생각이 들게 함. 그래서 차라리 placeholder는 없는 게 맞다고 생각하고, 정 넣을 거면 create 할 때만 넣는 게 좋다고 생각.

2020-11-28 05:30 UTC, davin111 commented on orange/src/containers/NecessityPage/NecessityPage.tsx
> +        <h1 className="NecessityPageBlock">집집</h1>
요건 무엇이져, 유저(is_leader)가 등록한 자신의 집 이름을 노출시켜야할 거 같은데? 항상 '집집'으로 뜨네

2020-11-28 05:30 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateOrUpdateForm/NecessityCreateOrUpdateForm.tsx
> +          helperText={errors.count && '가격을 입력해주세요!'}
이거 참고로 server 로직도 그렇고 기존에 price는 optional이었을 거야. 안 넣으면 기존에 DB에 존재하던 생필품의 경우에는 DB에 등록되어있는 price가 자동으로 보임.

2020-11-28 05:30 UTC, davin111 commented on orange/src/setupTests.ts
> +window.matchMedia = window.matchMedia || function () {
이거 이런 식으로 쓰는 거 antipattern이라는 거 같은데, 고쳐주면 좋긴 할듯.

2020-11-28 05:32 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateOrUpdateForm/NecessityCreateOrUpdateForm.tsx
> +          placeholder="크리넥스"
@davin111 혹시 예시말고 진짜 내용이라는건 뭘 말하는거야?? 유저들에게 보여주는 용으로 사용하는 placeholder가 필요없다는건지 아니면 다른 예시를 들자는건지??

2020-11-28 05:49 UTC, YeonghyeonKO commented on orange/src/components/Necessity/NecessityCreateOrUpdateForm/NecessityCreateOrUpdateForm.tsx
> +          placeholder="부드러운거임"
@davin111 이건 확실히 수정해야할 옳은 지적이군

2020-11-28 05:50 UTC, davin111 commented on orange/src/components/Necessity/NecessityCreateOrUpdateForm/NecessityCreateOrUpdateForm.tsx
> +          placeholder="크리넥스"
그냥 필요없다는 것. 특히 https://github.com/gongmyeong-study/orangenongjang/pull/70#discussion_r531890017 여기서 말하듯 오히려 혼란을 유발함.

2020-11-28 05:53 UTC, YeonghyeonKO commented
@davin111 https://github.com/gongmyeong-study/orangenongjang/pull/70#issuecomment-735040302
'어디갔냐'는 것은 내가 local에서 실행했을 때 현재 master branch에 merge한 타임라인 관련 PR ([ON-26](https://orangenongjang.atlassian.net/browse/ON-26))이 반영되지 않은 것 같다는 맥락이었습니당

2020-11-28 05:54 UTC, davin111 commented
@YeonghyeonKO 아 뭐 그건 사실 상관 없을 수 있는데, 불안하면 @JSKeum 이 현재 master를 이 branch로 한 번 merge해주면 좋을듯.

2020-11-29 02:08 UTC, JSKeum commented on orange/src/components/Necessity/NecessityCreateOrUpdateForm/NecessityCreateOrUpdateForm.tsx
> +          placeholder="부드러운거임"
로그인, 회원가입 form 제외하고 placeholder 다 지울게요!

2020-11-29 03:13 UTC, JSKeum commented on orange/src/containers/NecessityPage/NecessityPage.tsx
> +        <h1 className="NecessityPageBlock">집집</h1>
현재 house가 store로 관리되고 있지 않아서 그런데, house store 만들기 PR 하나 더 해서 그렇게 수정할게요

2020-11-29 03:16 UTC, JSKeum commented on orange/src/components/Necessity/NecessityList/NecessityList.tsx
> +              첫 생필품을 추가해보세요!
해결했습니다!

2020-11-29 03:19 UTC, JSKeum commented on orange/src/components/Necessity/NecessityCreateOrUpdateForm/NecessityCreateOrUpdateForm.tsx
> +    props.placeId, props.necessityToBeUpdated!.id, data.description, data.price, data.count,
update or create 분기를 타서 update인 경우에는 optional인 necessityToBeUpdated 가 존재하기 때문에 '!'를 사용했습니다. non-null-assertion 은 최대한 안쓰는게 좋긴한데.. 일단 이게 제일 간단해서 썼어요

2020-11-29 03:25 UTC, JSKeum commented on orange/src/setupTests.ts
> +window.matchMedia = window.matchMedia || function () {
slick 관련해서 test 에러난거 고치려고 넣은거예요 (https://github.com/gongmyeong-study/orangenongjang/pull/70/commits/c2f9963894a601b96fe51218384d37022eec73c6
어차피 테스트 안해서 상관없긴 한데 그래도 no named warning은 고쳐볼게요

2020-11-29 03:44 UTC, YeonghyeonKO approved these changes
Good

2020-11-29 05:54 UTC, davin111 approved these changes

2020-11-29 06:02 UTC, merged