ON-57 [front] Place 이름 수정 form
gongmyeong-study/orangenongjang pull request #86
Opened 2021-01-13 16:32 UTC by YeonghyeonKO

# Major Changes
> [Jira ON-57](https://orangenongjang.atlassian.net/browse/ON-57)

## 1. Place 이름 수정 버튼 생성
- hover 시에 연필 버튼이 보이게 되며, 이를 클릭 시 form이 표출되어 수정할 수 있게 함.

<img width="533" alt="스크린샷 2021-01-14 오전 1 29 46" src="https://user-images.githubusercontent.com/46114393/104480527-03e50580-5608-11eb-922b-91cd840888bf.png">

<br>

- Enter, unfocus 시에 input 값이 저장되며, ESC 누를 시에는 동작이 취소됨.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/46114393/104480655-27a84b80-5608-11eb-9229-395907e0dab9.png">

2021-01-14 01:23 UTC, YeonghyeonKO commented on orange/src/components/PlaceBox/PlaceBox.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
정의한 변수 모두 사용하고 있으므로 해당 라인 삭제하겠습니다.

2021-01-14 01:23 UTC, YeonghyeonKO commented on orange/src/store/actions/necessity/necessity.tsx
> +  `/api/v1/house/${houseId}/place/${placeId}/`, { houseId, placeId, name },
처음에 name 대신 placeName으로 썼다가 수정 시에 200 OK는 가는데 왜 수정이 안되는지 시간을 허비했네요

2021-01-14 03:55 UTC, YeonghyeonKO commented on orange/src/components/PlaceBox/PlaceBox.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
삭제완료

2021-01-14 05:32 UTC, JSKeum requested changes

2021-01-14 05:32 UTC, JSKeum commented on orange/src/components/PlaceBox/PlaceBox.tsx
> +        />
react-editext 모듈을 사용한 이유는 무엇인가요? weekly 다운로드 수가 적어서 신뢰가 좀 안 가는데, material form이나 그냥 html input 태그를 사용할 때보다 어떤 장점이 있나요?

2021-01-14 05:32 UTC, JSKeum commented on orange/src/components/PlaceBox/PlaceBox.tsx
> +        : (null)}
`isPlaceRenamed && onRenamePlace(place.house_id, place.id, placeToBeRenamed)`로 적는 게 깔끔할 것 같습니다. 그런데 이 코드가 이해가 되지 않는데, onRenamePlace api 함수를 그냥 html 안에 집어 넣은 건가요?

2021-01-14 05:32 UTC, JSKeum commented on orange/src/components/PlaceBox/PlaceBox.tsx
> +  const [placeToBeRenamed, setPlaceToBeRenamed] = useState(place.name);
props와 state는 역할이 다릅니다. 불변하는 값인 props를 state에 넣으면 안 됩니다. API로 DB를 업데이트한 다음 프론트 단에서 업데이트된 이름을 보여주기 위한 것일 텐데, 이렇게 하는 것보다 API Response를 받아 redux로 해당 place가 변하는 걸 감지하여 이 PlaceBox를 새로 렌더링하도록 하는게(부모 컴포넌트에서 새 props를 주는 것) 좋은 방식일 것 같습니다.

https://lucybain.com/blog/2016/react-state-vs-pros/

2021-01-15 08:57 UTC, YeonghyeonKO commented on orange/src/components/PlaceBox/PlaceBox.tsx
> +        />
material form도 찾아보긴 했는데 제가 원하던 스펙이 없는 것 같아서 editext를 사용했는데 별로일까요?

2021-01-15 08:57 UTC, YeonghyeonKO commented on orange/src/components/PlaceBox/PlaceBox.tsx
> +        : (null)}
@JSKeum 
1. `isPlaceRenamed && onRenamePlace(place.house_id, place.id, placeToBeRenamed)`로 수정했습니다.
2. 네 맞습니다

2021-01-19 13:35 UTC, YeonghyeonKO commented on orange/src/components/PlaceBox/PlaceBox.tsx
> +  const [placeToBeRenamed, setPlaceToBeRenamed] = useState(place.name);
@JSKeum 
1. props는 하나의 렌더링 싸이클에서만 불변하지 않나요? 여기서 **place.name**이 **props**인데 useState를 통해 **placeToBeRenamed** state를 만들면 place.name은 그대로 불변하고 placeToBeRenamed만 변해서 상관없지 않나 해서요. 

2. redux를 사용하자는 말은 불필요하게 props를 전달하는 과정에서 생기는 data flow를 최소화하기 위해 store에서 꺼내쓰자는 말인거죠?

2021-01-22 09:13 UTC, JSKeum commented on orange/src/components/PlaceBox/PlaceBox.tsx
> +  const [placeToBeRenamed, setPlaceToBeRenamed] = useState(place.name);
지금 상태로 해도 컴파일 에러나 당장 런타임 에러는 나지 않을 것 같은데, 그렇다 해도 장기적으로 데이터 흐름이 꼬일 가능성이 높고 의미상 좋지 않아 보입니다. DB에 있는 정보를 보여줘야 하는 것을 front에서 알아서 처리하려고 하기 때문에 이상한 것 같은데, Place를 수정한 다음 response 결과값을 보고 그 값으로 업데이트할 수 있지 않을까요?

2021-01-24 08:17 UTC, YeonghyeonKO commented on orange/src/components/PlaceBox/PlaceBox.tsx
> +  const [placeToBeRenamed, setPlaceToBeRenamed] = useState(place.name);
굳이 useState를 안써도 해결되는 문제였군요

2021-01-24 08:27 UTC, JSKeum approved these changes

2021-01-24 08:43 UTC, merged